Repository StackStorm/st2, pull requests merged in 2018-11, with the labels that each got.

#4424 Various Python 3 related fixes and changes
  CHANGELOG.rst
  Makefile
  conf/st2.conf.sample
  contrib/packs/tests/test_action_download.py
  st2actions/st2actions/notifier/scheduler.py
  st2common/st2common/config.py
  st2common/st2common/models/db/trace.py
  st2common/st2common/util/pack_management.py
  st2reactor/st2reactor/garbage_collector/base.py
  st2reactor/st2reactor/timer/config.py
  tools/launchdev.sh
  tox.ini
Labels: python3

#4428 More Python 3 fixes
  Makefile
  contrib/examples/requirements.txt
  contrib/examples/sensors/echo_flask_app.py
  contrib/examples/sensors/fibonacci_sensor.py
  st2common/bin/st2-run-pack-tests
  st2common/bin/st2-self-check
  st2common/bin/st2ctl
  st2common/st2common/util/monkey_patch.py
Labels: python3

#4445 Add new "metadata_file" attribute to all the pack resource models
  CHANGELOG.rst
  st2actions/tests/unit/test_actions_registrar.py
  st2api/st2api/controllers/v1/actions.py
  st2api/tests/unit/controllers/v1/test_packs.py
  st2common/st2common/bootstrap/actionsregistrar.py
  st2common/st2common/bootstrap/aliasesregistrar.py
  st2common/st2common/bootstrap/policiesregistrar.py
  st2common/st2common/bootstrap/rulesregistrar.py
  st2common/st2common/bootstrap/sensorsregistrar.py
  st2common/st2common/bootstrap/triggersregistrar.py
  st2common/st2common/content/utils.py
  st2common/st2common/models/api/action.py
  st2common/st2common/models/api/policy.py
  st2common/st2common/models/api/rule.py
  st2common/st2common/models/api/sensor.py
  st2common/st2common/models/api/trigger.py
  st2common/st2common/models/db/action.py
  st2common/st2common/models/db/actionalias.py
  st2common/st2common/models/db/rule.py
  st2common/st2common/models/db/rule_enforcement.py
  st2common/st2common/models/db/sensor.py
  st2common/st2common/models/db/stormbase.py
  st2common/st2common/models/db/trigger.py
  st2common/st2common/models/utils/sensor_type_utils.py
  st2common/st2common/services/triggers.py
  st2common/tests/unit/test_aliasesregistrar.py
  st2common/tests/unit/test_content_utils.py
  st2common/tests/unit/test_policies_registrar.py
  st2reactor/tests/integration/test_sensor_container.py
  st2reactor/tests/unit/test_sensor_and_rule_registration.py
  st2tests/st2tests/action_aliases.py
  tools/migrate_rules_to_include_pack.py
Labels: API

#4444 Add get_children method to st2client for liveactions
  st2client/st2client/models/core.py
  st2client/tests/unit/test_client_liveaction.py
Labels: component:st2client

#4450 More Python 3 compatibility fixes
  contrib/examples/actions/pythonactions/fibonacci.py
  contrib/examples/actions/pythonactions/forloop_parse_github_repos.py
  contrib/examples/actions/pythonactions/forloop_push_github_repos.py
  st2api/st2api/controllers/exp/validation.py
  st2api/st2api/controllers/v1/actionexecutions.py
  st2api/st2api/controllers/v1/aliasexecution.py
  st2api/st2api/controllers/v1/timers.py
  st2auth/st2auth/handlers.py
  st2client/st2client/commands/auth.py
  st2client/st2client/commands/pack.py
  st2client/st2client/commands/resource.py
  st2common/bin/st2-track-result
  st2common/st2common/bootstrap/actionsregistrar.py
  st2common/st2common/router.py
  st2common/st2common/runners/paramiko_ssh.py
  st2common/st2common/services/sensor_watcher.py
  st2common/st2common/services/triggerwatcher.py
  st2common/st2common/transport/connection_retry_wrapper.py
  st2common/st2common/util/virtualenvs.py
  st2common/st2common/util/workflow/mistral.py
  st2common/st2common/validators/workflow/mistral/v2.py
Labels: python3

#4449 Rename st2client.liveactions to st2client.executions
  CHANGELOG.rst
  st2client/README.rst
  st2client/st2client/client.py
  st2client/st2client/commands/action.py
  st2client/st2client/commands/pack.py
  st2client/st2client/commands/trace.py
  st2client/st2client/models/action.py
  st2client/st2client/models/core.py
  st2client/tests/unit/test_client_executions.py
  st2tests/integration/mistral/base.py
  st2tests/integration/mistral/test_wiring_cancel.py
  st2tests/integration/mistral/test_wiring_pause_resume.py
  st2tests/integration/mistral/test_wiring_rerun.py
  st2tests/integration/orquesta/base.py
  st2tests/integration/orquesta/test_wiring_cancel.py
  st2tests/integration/orquesta/test_wiring_pause_and_resume.py
  st2tests/integration/orquesta/test_wiring_with_items.py
Labels: component:st2client

#4388 Check and warn if action ref is not present during alias registration
  CHANGELOG.rst
  contrib/packs/tests/test_action_unload.py
  st2common/st2common/bootstrap/aliasesregistrar.py
  st2tests/st2tests/fixtures/packs/dummy_pack_1/aliases/alias_noaction_ref_reg.yaml
Labels: chatops
