Repository StackStorm/st2, pull requests merged in 2018-06, with the labels that each got.

#4149 Experimental and opt-in Python 3 support for Python runner actions
  CHANGELOG.rst
  contrib/examples/actions/python_runner_print_python_version.yaml
  contrib/examples/actions/pythonactions/print_python_version.py
  contrib/runners/python_runner/python_runner/python_runner.py
  contrib/runners/python_runner/tests/unit/test_pythonrunner.py
  st2client/st2client/commands/pack.py
  st2common/st2common/constants/pack.py
  st2common/st2common/util/sandboxing.py
  st2common/st2common/util/virtualenvs.py
  st2common/tests/unit/test_util_sandboxing.py
  st2common/tests/unit/test_virtualenvs.py
  st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume.yaml
Labels: python3

#4158 Fix sharing st2 logs when CircleCI task failed
  circle.yml
Labels: bug

#4168 Fix an issue with friendly error not being thrown if validation failed on config item of type array
  CHANGELOG.rst
  st2common/st2common/util/pack.py
  st2common/tests/unit/test_configs_registrar.py
  st2tests/st2tests/fixtures/packs/configs/dummy_pack_19.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_19/config.schema.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_19/pack.yaml
Labels: bug

#4172 Fix nginx 'proxy_pass' directive can't use URI in regex location
  conf/nginx/st2.conf
Labels: RFR

#4165 Move from keyczar to cryptography library for symmetric encryption / decryption
  conf/st2.conf.sample
  contrib/runners/python_runner/tests/unit/test_pythonrunner.py
  fixed-requirements.txt
  requirements.txt
  st2common/bin/st2-generate-symmetric-crypto-key
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2common/st2common/config.py
  st2common/st2common/util/crypto.py
  st2common/tests/unit/test_crypto_utils.py
  st2tests/st2tests/fixtures/keyczar_keys/five.json
  st2tests/st2tests/fixtures/keyczar_keys/four.json
  st2tests/st2tests/fixtures/keyczar_keys/one.json
  st2tests/st2tests/fixtures/keyczar_keys/three.json
  st2tests/st2tests/fixtures/keyczar_keys/two.json
  test-requirements.txt
  tox.ini
Labels: python3

#4179 Add single sensor mode to the sensor container service / process
  .travis.yml
  Makefile
  conf/st2.conf.sample
  conf/st2.tests.conf
  conf/st2.tests1.conf
  contrib/hello_st2/config.yaml
  st2common/st2common/constants/scheduler.py
  st2common/st2common/router.py
  st2common/tests/integration/test_register_content_script.py
  st2debug/st2debug/cmd/submit_debug_info.py
  st2debug/tests/integration/fixtures/configs/st2.conf
  st2exporter/st2exporter/exporter/dumper.py
  st2exporter/st2exporter/worker.py
  st2exporter/tests/integration/test_dumper_integration.py
  st2exporter/tests/integration/test_export_worker.py
  st2exporter/tests/unit/test_dumper.py
  st2exporter/tests/unit/test_json_converter.py
  st2reactor/st2reactor/cmd/sensormanager.py
  st2reactor/st2reactor/container/manager.py
  st2reactor/st2reactor/container/partitioner_lookup.py
  st2reactor/st2reactor/container/process_container.py
  st2reactor/st2reactor/sensor/config.py
  st2reactor/tests/integration/test_garbage_collector.py
  st2reactor/tests/integration/test_sensor_container.py
  st2tests/st2tests/config.py
  tox.ini
Labels: HA, python3

#4183 Python 3 fixes and changes for st2auth, st2actions, st2stream
  .travis.yml
  contrib/runners/python_runner/tests/integration/test_python_action_process_wrapper.py
  st2actions/tests/unit/test_paramiko_ssh.py
  st2actions/tests/unit/test_runner_container.py
  st2actions/tests/unit/test_worker.py
  st2auth/st2auth/handlers.py
  st2auth/tests/unit/controllers/v1/test_token.py
  st2auth/tests/unit/test_handlers.py
  st2common/st2common/runners/paramiko_ssh.py
  st2stream/st2stream/controllers/v1/stream.py
  st2stream/tests/unit/controllers/v1/test_rbac_for_supported_endpoints.py
  st2stream/tests/unit/controllers/v1/test_stream.py
  tox.ini
Labels: python3

#4194 Fix wrong information for /api/v1/apikeys/ doc
  st2common/st2common/openapi.yaml
  st2common/st2common/openapi.yaml.j2
Labels: bug, documentation

#4196 Rename a misleading variable name
  st2api/st2api/controllers/v1/pack_configs.py
  st2common/st2common/openapi.yaml
  st2common/st2common/openapi.yaml.j2
Labels: enhancement

#4206 Add gunicorn logging config for all the API services which run under gunicorn
  st2api/conf/logging.gunicorn.conf
  st2auth/conf/logging.gunicorn.conf
  st2stream/conf/logging.gunicorn.conf
Labels: bug
