Repository StackStorm/st2, pull requests merged in 2018-07, with the labels that each got.

#4226 ?include_attributes regression fix for /v1/executions API endpoint, update openapi.yaml
  CHANGELOG.rst
  st2api/st2api/controllers/v1/actionexecutions.py
  st2api/tests/unit/controllers/v1/test_executions.py
  st2common/st2common/openapi.yaml
  st2common/st2common/openapi.yaml.j2
Labels: API, bug

#4225 Only set req.body to an empty JSON object when content type is application/json
  st2common/st2common/router.py
Labels: API

#4242 Allow user to force terminal size used by the CLI formatters by setting environment variable
  CHANGELOG.rst
  st2client/st2client/formatters/table.py
  st2client/st2client/utils/terminal.py
  st2client/tests/unit/test_util_terminal.py
Labels: enhancement

#4264 Various test speed ups
  .travis.yml
  Makefile
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2common/tests/unit/test_db.py
  st2tests/st2tests/base.py
Labels: performance

#4271 Remove use of async in args for python 3.7 support
  st2client/st2client/commands/action.py
Labels: python3

#4272 More coverage improvements
  .travis.yml
  scripts/travis/install-and-run-mongodb.sh
  scripts/travis/mongod.conf
  scripts/travis/submit-codecov-coverage.sh
  st2common/st2common/models/db/__init__.py
  st2common/st2common/models/db/actionalias.py
  st2common/st2common/models/db/sensor.py
  st2common/st2common/models/db/workflow.py
  st2common/st2common/rbac/migrations.py
  st2common/tests/unit/test_rbac_syncer.py
  st2tests/st2tests/base.py
Labels: performance

#4275 More Travis CI changes
  .travis.yml
  Makefile
  scripts/travis/prepare-integration.sh
  st2actions/tests/integration/test_notifier.py
  st2api/tests/integration/test_gunicorn_configs.py
  st2common/st2common/constants/scheduler.py
  st2common/st2common/constants/timer.py
  st2common/tests/integration/test_register_content_script.py
  st2reactor/tests/integration/test_rules_engine.py
  tox.ini
Labels: performance

#4256 Add a new standalone st2-pack-install CLI command for installing a pack
  CHANGELOG.rst
  contrib/packs/actions/pack_mgmt/download.py
  contrib/packs/actions/pack_mgmt/setup_virtualenv.py
  contrib/packs/tests/test_action_download.py
  scripts/travis/install-and-run-mongodb.sh
  st2common/bin/st2-pack-download
  st2common/bin/st2-pack-install
  st2common/bin/st2-pack-setup-virtualenv
  st2common/setup.py
  st2common/st2common/cmd/download_pack.py
  st2common/st2common/cmd/install_pack.py
  st2common/st2common/cmd/purge_executions.py
  st2common/st2common/cmd/purge_trigger_instances.py
  st2common/st2common/cmd/setup_pack_virtualenv.py
  st2common/st2common/cmd/validate_config.py
  st2common/st2common/config.py
  st2common/st2common/models/db/__init__.py
  st2common/st2common/util/pack_management.py
  st2common/st2common/util/virtualenvs.py
  st2common/tests/unit/test_pack_management.py
  st2reactor/st2reactor/cmd/rule_tester.py
  st2reactor/st2reactor/container/process_container.py
Labels: Docker, K8s, RFR
