Repository StackStorm/st2, pull requests merged in 2019-04, with the labels that each got.

#4622 st2-self-check should ignore any pack actions which name doesn't start with "test_"
  st2common/bin/st2-self-check
Labels: bug

#4623 Fix erroneous carriage return character (\r) in the output of remote shell script and command actions
  CHANGELOG.rst
  st2common/st2common/runners/paramiko_ssh.py
  st2common/st2common/util/misc.py
  st2common/tests/unit/test_misc_utils.py
Labels: bug, runners

#4621 Use correct gunicorn logging config with st2 packages (don't include AUDIT log messages in non-AUDIT log file)
  CHANGELOG.rst
  conf/st2.package.conf
Labels: bug, logging

#4630 Log non-fatal errors during service bootstrap phase under DEBUG instead of ERROR
  CHANGELOG.rst
  st2common/st2common/services/triggers.py
  st2common/st2common/triggers.py
Labels: bug

#4632 Trstruth/st2client user filter
  CHANGELOG.rst
  st2client/st2client/commands/action.py
Labels: CLI

#4634 Fixed a problem not to decrypt user scope data store value in Jinja expression
  CHANGELOG.rst
  contrib/examples/actions/chains/decrypt_kv_jinja_filter.yaml
  contrib/runners/action_chain_runner/action_chain_runner/action_chain_runner.py
  st2common/st2common/expressions/functions/datastore.py
  st2common/st2common/services/keyvalues.py
  st2common/tests/unit/test_jinja_render_crypto_filters.py
Labels: bug, enhancement

#4611 Fix Missing parameters in linux.wait_for_ssh
  CHANGELOG.rst
  contrib/linux/actions/wait_for_ssh.yaml
Labels: CLI, bug, component:st2client

#4638 Add example action for testing "st2 execution tail" functionality with Orquesta workflows
  CHANGELOG.rst
  contrib/examples/actions/orquesta-streaming-demo.meta.yaml
  contrib/examples/actions/workflows/orquesta-streaming-demo.yaml
Labels: workflows: orquesta

#4601 Correctly handle unicode data in the HTTP runner
  CHANGELOG.rst
  contrib/runners/http_runner/http_runner/http_runner.py
  contrib/runners/http_runner/tests/unit/test_http_runner.py
Labels: bug

#4637 Update dependencies to latest versions
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2client/requirements.txt
  st2common/requirements.txt
Labels: external dependency

#4645 Throw a more user-friendly error on permission denied when trying to to write a pack data file
  CHANGELOG.rst
  st2api/st2api/controllers/v1/actions.py
  st2common/bin/st2-self-check
  st2common/st2common/util/pack_management.py
Labels: API, bug
