Repository StackStorm/st2, pull requests merged in 2019-10, with the labels that each got.

#4796 Add fastly among adopters
  ADOPTERS.md
Labels: size/XS

#4786 Add support for immutable_parameters in action aliases
  CHANGELOG.rst
  st2api/st2api/controllers/v1/aliasexecution.py
  st2api/tests/unit/controllers/v1/test_alias_execution.py
  st2common/st2common/models/api/action.py
  st2common/st2common/models/db/actionalias.py
  st2common/st2common/models/utils/action_alias_utils.py
  st2common/tests/unit/test_action_alias_utils.py
  st2tests/st2tests/fixtures/aliases/aliases/alias5.yaml
Labels: chatops, feature, size/L

#4791 GET entrypoint of a workflow from st2client
  CHANGELOG.rst
  st2client/st2client/client.py
  st2client/st2client/models/action.py
  st2client/st2client/models/core.py
  st2client/tests/unit/test_client_actions.py
Labels: size/L

#4803 fixing subprocess to use system buffer instead of being unbuffered
  CHANGELOG.rst
  conf/st2.conf.sample
  contrib/runners/python_runner/python_runner/python_runner.py
  contrib/runners/python_runner/tests/unit/test_pythonrunner.py
  scripts/travis/prepare-integration.sh
  st2common/st2common/config.py
  st2common/st2common/util/green/shell.py
  st2tests/st2tests/resources/packs/pythonactions/actions/pascal_row.py
  st2tests/st2tests/resources/packs/pythonactions/actions/print_to_stdout_and_stderr.py
  tools/launchdev.sh
  tools/screen-configs/st2actionrunner.conf
  tools/screen-configs/st2api.conf
  tools/screen-configs/st2auth.conf
  tools/screen-configs/st2garbagecollector.conf
  tools/screen-configs/st2notifier.conf
  tools/screen-configs/st2resultstracker.conf
  tools/screen-configs/st2rulesengine.conf
  tools/screen-configs/st2scheduler.conf
  tools/screen-configs/st2sensorcontainer.conf
  tools/screen-configs/st2stream.conf
  tools/screen-configs/st2timersengine.conf
  tools/screen-configs/st2workflowengine.conf
Labels: feature: real time action output streaming, service: action runner, size/XS

#4792 Don't call eventlet directly inside the st2reactor code
  CHANGELOG.rst
  conf/st2.conf.sample
  st2common/st2common/config.py
  st2common/st2common/log.py
  st2common/st2common/util/concurrency.py
  st2common/st2common/util/virtualenvs.py
  st2reactor/st2reactor/cmd/timersengine.py
  st2reactor/st2reactor/container/manager.py
  st2reactor/st2reactor/container/process_container.py
  st2reactor/st2reactor/garbage_collector/base.py
  st2reactor/st2reactor/sensor/base.py
  st2reactor/tests/integration/test_garbage_collector.py
  st2reactor/tests/integration/test_rules_engine.py
  st2reactor/tests/integration/test_sensor_container.py
  st2reactor/tests/integration/test_sensor_watcher.py
  st2reactor/tests/unit/test_process_container.py
Labels: size/M

#4807 /v1/rules API endpoint action parameters secrets masking (additional changes on top of #4788)
  CHANGELOG.rst
  st2api/st2api/controllers/v1/rule_views.py
  st2api/st2api/controllers/v1/rules.py
  st2api/tests/unit/controllers/v1/test_rules.py
  st2common/st2common/models/db/rule.py
  st2common/st2common/openapi.yaml
  st2common/st2common/openapi.yaml.j2
  st2common/tests/unit/test_db.py
  st2tests/st2tests/fixtures/generic/actions/action1.yaml
  st2tests/st2tests/fixtures/generic/rules/rule1.yaml
Labels: service: api, size/L

#4808 Add try block to handle get config errors in render_final_params
  st2common/st2common/util/param.py
Labels: size/S

#4809 Fix a bug with authentication API endpoint returning internal server error under gunicorn if auth.api_url config option was not set
  CHANGELOG.rst
  st2auth/st2auth/controllers/v1/auth.py
  st2auth/tests/unit/controllers/v1/test_token.py
Labels: bug, component:st2auth, service: auth api, size/S
