Repository StackStorm/st2, pull requests merged in 2019-07, with the labels that each got.

#4733 Fix the garbage collection for orquesta workflow executions
  conf/st2.conf.sample
  st2common/st2common/config.py
  st2common/st2common/services/workflows.py
  st2reactor/tests/unit/test_garbage_collector.py
Labels: bug, workflows: orquesta

#4734 Fix the garbage collection for orquesta workflow executions (v3.1)
  conf/st2.conf.sample
  st2common/st2common/config.py
  st2common/st2common/services/workflows.py
  st2reactor/tests/unit/test_garbage_collector.py
Labels: bug

#4738 Add improved Github issues templates, new security template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
  SECURITY.md
Labels: enhancement

#4723 Set content-length to 0 in logging messages when return value is a Generator
  CHANGELOG.rst
  st2common/st2common/middleware/logging.py
Labels: bug

#4743 Install pack with the latest tag
  CHANGELOG.rst
  contrib/packs/tests/test_action_download.py
  st2common/st2common/util/pack_management.py
Labels: enhancement

#4732 Update dig.py error handling
  CHANGELOG.rst
  contrib/linux/README.md
  contrib/linux/actions/dig.py
  contrib/linux/pack.yaml
Labels: enhancement, external dependency, python3, runners
