Repository StackStorm/st2, pull requests merged in 2019-08, with the labels that each got.

#4754 Fix code coverage for ci-integration make tests target, speed up some Orquesta integration tests
  Makefile
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2tests/integration/orquesta/base.py
  st2tests/integration/orquesta/test_wiring_error_handling.py
Labels: code coverage, tests, tests: speed optimization

#4757 Add support for blacklisting hosts to the HTTP runner
  CHANGELOG.rst
  contrib/runners/http_runner/http_runner/http_runner.py
  contrib/runners/http_runner/http_runner/runner.yaml
  contrib/runners/http_runner/tests/unit/test_http_runner.py
Labels: runners, runners: http

#4760 Pattern for running particular Travis tasks as part of a nightly build
  .travis.yml
  Makefile
  scripts/travis/run-nightly-make-task-if-exists.sh
  tox.ini
Labels: infrastructure: ci/cd, tests, travisci

#4763 Fix nightly build
  Makefile
Labels: tests, travisci

#4768 Fix copy/paste typo
  contrib/core/actions/local_sudo.yaml
Labels: complexity:easy, documentation, size/XS, status:not an issue

#4767 Update various Python dependencies to latest stable versions
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2actions/requirements.txt
  st2api/requirements.txt
  st2api/tests/unit/controllers/v1/test_actions.py
  st2auth/requirements.txt
  st2client/requirements.txt
  st2common/requirements.txt
  st2debug/requirements.txt
  st2exporter/requirements.txt
  st2reactor/requirements.txt
  st2stream/requirements.txt
  st2tests/requirements.txt
  test-requirements.txt
Labels: external dependency

#4774 Fix dependency conflicts
  CHANGELOG.rst
  Makefile
  contrib/runners/action_chain_runner/dist_utils.py
  contrib/runners/action_chain_runner/requirements.txt
  contrib/runners/announcement_runner/dist_utils.py
  contrib/runners/announcement_runner/requirements.txt
  contrib/runners/http_runner/dist_utils.py
  contrib/runners/http_runner/requirements.txt
  contrib/runners/inquirer_runner/dist_utils.py
  contrib/runners/inquirer_runner/requirements.txt
  contrib/runners/local_runner/dist_utils.py
  contrib/runners/local_runner/requirements.txt
  contrib/runners/mistral_v2/dist_utils.py
  contrib/runners/mistral_v2/requirements.txt
  contrib/runners/noop_runner/dist_utils.py
  contrib/runners/noop_runner/requirements.txt
  contrib/runners/orquesta_runner/dist_utils.py
  contrib/runners/orquesta_runner/requirements.txt
  contrib/runners/python_runner/dist_utils.py
  contrib/runners/python_runner/requirements.txt
  contrib/runners/remote_runner/dist_utils.py
  contrib/runners/remote_runner/requirements.txt
  contrib/runners/winrm_runner/dist_utils.py
  contrib/runners/winrm_runner/requirements.txt
  fixed-requirements.txt
  requirements.txt
  scripts/fixate-requirements.py
  scripts/write-headers.sh
  st2actions/dist_utils.py
  st2actions/requirements.txt
  st2api/dist_utils.py
  st2api/requirements.txt
  st2auth/dist_utils.py
  st2auth/requirements.txt
  st2client/dist_utils.py
  st2client/requirements.txt
  st2common/dist_utils.py
  st2common/requirements.txt
  st2common/st2common/constants/pack.py
  st2common/tests/fixtures/requirements-used-for-tests.txt
  st2common/tests/unit/test_dist_utils.py
  st2debug/dist_utils.py
  st2debug/requirements.txt
  st2exporter/dist_utils.py
  st2exporter/requirements.txt
  st2reactor/dist_utils.py
  st2reactor/requirements.txt
  st2stream/dist_utils.py
  st2stream/requirements.txt
  st2tests/dist_utils.py
  st2tests/requirements.txt
Labels: amqp, bug, complexity:medium, regression
