Repository StackStorm/st2, pull requests merged in 2019-12, with the labels that each got.

#4826 Utilize st2common.util.concurrency wrapper in st2common
  contrib/runners/python_runner/python_runner/python_runner.py
  st2common/st2common/runners/base.py
  st2common/st2common/runners/parallel_ssh.py
  st2common/st2common/runners/paramiko_ssh.py
  st2common/st2common/runners/utils.py
  st2common/st2common/services/sensor_watcher.py
  st2common/st2common/services/triggerwatcher.py
  st2common/st2common/transport/connection_retry_wrapper.py
  st2common/st2common/transport/consumers.py
  st2common/st2common/util/concurrency.py
  st2common/st2common/util/shell.py
Labels: size/L

#4829 #4795 fix 'core.sendmail' for subject line wrapping
  CHANGELOG.rst
  contrib/core/actions/send_mail/send_mail
  contrib/core/pack.yaml
Labels: bug, size/XS

#4820 Pass `route` from trigger-instance to post_result
  contrib/chatops/CHANGES.md
  contrib/chatops/README.md
  contrib/chatops/actions/post_result.yaml
  contrib/chatops/actions/workflows/post_result.yaml
  contrib/chatops/pack.yaml
Labels: size/XS

#4831 Update rule comparison operators to work with mixed operator types (bytes and strings)
  CHANGELOG.rst
  contrib/hello_st2/pack.yaml
  st2common/st2common/operators.py
  st2common/tests/unit/test_operators.py
Labels: python3, size/L

#4834 Fix SSL support for MongoDB and RabbitMQ under Python 3.x
  CHANGELOG.rst
  conf/st2.conf.sample
  st2api/st2api/app.py
  st2api/st2api/cmd/api.py
  st2api/st2api/wsgi.py
  st2auth/st2auth/app.py
  st2auth/st2auth/wsgi.py
  st2common/st2common/config.py
  st2common/st2common/models/db/__init__.py
  st2common/tests/unit/test_db.py
  st2tests/st2tests/base.py
Labels: mongodb, python3, rabbitmq, size/L, ssl

#4835 Update pymongo to the latest version
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2api/requirements.txt
  st2auth/requirements.txt
  st2common/requirements.txt
  st2common/st2common/models/db/__init__.py
  st2stream/requirements.txt
Labels: external dependency, mongodb, size/XS

#4833 Add support for orquesta task retry
  CHANGELOG.rst
  contrib/examples/actions/orquesta-task-retry-exhausted.yaml
  contrib/examples/actions/orquesta-task-retry.yaml
  contrib/examples/actions/workflows/orquesta-task-retry-exhausted.yaml
  contrib/examples/actions/workflows/orquesta-task-retry.yaml
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2tests/integration/orquesta/test_wiring_task_retry.py
Labels: size/L
