Repository StackStorm/st2, pull requests merged in 2019-11, with the labels that each got.

#4811 Add Verizon to the list of Adopters
  ADOPTERS.md
Labels: feature, size/XS

#4814 Refactor handling of with items result
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2common/st2common/services/workflows.py
Labels: size/M

#4817 Remove automatic rendering of workflow output when updating task state
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2common/st2common/services/workflows.py
  st2tests/integration/orquesta/test_wiring_error_handling.py
Labels: size/S

#4819 Update pip dependencies, fix conflicting dependency version, ensure there are no conflicting dependencies
  CHANGELOG.rst
  Makefile
  contrib/linux/requirements.txt
  fixed-requirements.txt
  requirements.txt
  st2actions/in-requirements.txt
  st2actions/requirements.txt
  st2api/requirements.txt
  st2auth/requirements.txt
  st2client/requirements.txt
  st2common/requirements.txt
  st2debug/requirements.txt
  st2exporter/requirements.txt
  st2reactor/requirements.txt
  st2stream/requirements.txt
  test-requirements.txt
Labels: external dependency, size/L
