Repository StackStorm/st2, pull requests merged in 2019-01, with the labels that each got.

#4491 Fix a bug with trigger payload validation in linux.FileWatchSensor sensor
  contrib/linux/sensors/file_watch_sensor.py
  st2common/st2common/services/trigger_dispatcher.py
  st2common/st2common/validators/api/reactor.py
  st2reactor/tests/unit/test_sensor_service.py
Labels: bug

#4474 Add new "python_versions" attribute to the pack metadata file
  contrib/packs/tests/test_action_download.py
  st2common/st2common/models/api/pack.py
  st2common/st2common/models/db/pack.py
  st2common/st2common/util/pack_management.py
  st2common/st2common/util/versioning.py
  st2common/tests/unit/test_resource_registrar.py
  st2common/tests/unit/test_versioning_utils.py
  st2tests/st2tests/fixtures/packs/dummy_pack_20/pack.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_21/pack.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_9/pack.yaml
Labels: python3

#4495 Move inquiries API path from /exp to /v1
  CHANGELOG.rst
  st2api/st2api/controllers/v1/inquiries.py
  st2api/tests/base.py
  st2api/tests/unit/controllers/v1/test_inquiries.py
  st2api/tests/unit/controllers/v1/test_inquiries_rbac.py
  st2client/st2client/client.py
  st2common/st2common/openapi.yaml
  st2common/st2common/openapi.yaml.j2
Labels: API

#4505 Fix (workaround) for very slow test runs and timeouts on Travis CI
  st2common/st2common/transport/connection_retry_wrapper.py
  st2common/tests/unit/test_connection_retry_wrapper.py
Labels: tests, travisci

#4501 Fix intermediate test failures in scheduler tests
  Makefile
  fixed-requirements.txt
  st2actions/tests/unit/test_scheduler.py
  st2common/bin/st2-run-pack-tests
  test-requirements.txt
Labels: tests, travisci

#4507 Add amqp package to st2common
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: bug

#4509 Improve RabbitMQ connection retry code
  st2common/st2common/transport/connection_retry_wrapper.py
Labels: amqp, bug, rabbitmq

#4512 Remove redundant action-aliases for pack install
  CHANGELOG.rst
  contrib/packs/aliases/pack_install.yaml
  st2client/st2client/commands/action_alias.py
Labels: chatops

#4517 Suppress statsd library debug log messages in sensor container when DEBUG mode is not enabled
  st2reactor/st2reactor/container/sensor_wrapper.py
  test-requirements.txt
Labels: bug

#4504 Various fixes so our code also works with Travis Xenial VM image
  .circle/add-itest-user.sh
  .travis.yml
  Makefile
  contrib/runners/local_runner/tests/integration/test_localrunner.py
  requirements.txt
  scripts/travis/install-requirements.sh
  scripts/travis/prepare-integration.sh
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2reactor/tests/integration/test_garbage_collector.py
  st2tests/st2tests/fixtures/localrunner_pack/actions/text_gen.py
  test-requirements.txt
  tox.ini
Labels: tests, travisci

#4519 Don't submit metrics for any of the "get one" API endpoints
  st2common/st2common/middleware/instrumentation.py
  st2common/st2common/util/sandboxing.py
Labels: API, metrics

#4518 Add script for sending StackStorm service / process level metrics to statsd
  tools/submit-per-service-metrics-to-statsd
Labels: metrics

#4521 Upgrade python-gnupg dependency
  fixed-requirements.txt
  requirements.txt
Labels: external dependency
