Repository StackStorm/st2, pull requests merged in 2019-05, with the labels that each got.

#4661 Correctly use port specified in the SSH config file in the remote SSH runner
  CHANGELOG.rst
  contrib/runners/remote_runner/remote_runner/runner.yaml
  st2actions/tests/unit/test_paramiko_ssh.py
  st2common/st2common/runners/parallel_ssh.py
  st2common/st2common/runners/paramiko_ssh.py
  st2tests/st2tests/resources/ssh/empty_config
  st2tests/st2tests/resources/ssh/ssh_config_custom_port
Labels: bug, runners

#4662 Update pack install action so it works correctly when --python3 flag and "python_versions" pack.yaml attribute is used
  CHANGELOG.rst
  contrib/packs/actions/download.yaml
  contrib/packs/actions/pack_mgmt/download.py
  contrib/packs/actions/workflows/install.yaml
  contrib/packs/tests/test_action_download.py
  st2common/st2common/cmd/download_pack.py
  st2common/st2common/cmd/install_pack.py
  st2common/st2common/util/pack_management.py
Labels: bug

#4656 Revert part of #4609, fixes #4650
  CHANGELOG.rst
  st2api/st2api/controllers/v1/aliasexecution.py
  st2api/tests/unit/controllers/v1/test_alias_execution.py
Labels: API, bug, chatops

#4668 isotime formatter: assume incoming epoch timestamp being in UTC
  CHANGELOG.rst
  st2common/st2common/util/isotime.py
  st2common/tests/unit/test_isotime_utils.py
Labels: API, bug

#4671 Paswordless typo fix
  contrib/core/tests/test_action_sendmail.py
  contrib/runners/local_runner/local_runner/runner.yaml
  contrib/runners/remote_runner/remote_runner/runner.yaml
Labels: bug, documentation

#4673 Fix & Update nginx example confings for HA setup
  conf/HA/nginx/st2.conf.blueprint.sample
  conf/HA/nginx/st2.conf.controller.sample
Labels: HA, RFR, bug, enhancement

#4666 Fix PYTHONPATH handling for Python runner actions using --python3 flag
  CHANGELOG.rst
  contrib/hello_st2/pack.yaml
  st2common/st2common/util/sandboxing.py
  st2common/tests/unit/test_util_sandboxing.py
Labels: bug, python3, runners

#4674 Improve the approach we use to determine Python 3 system lib path
  CHANGELOG.rst
  conf/st2.conf.sample
  st2common/st2common/config.py
  st2common/st2common/util/sandboxing.py
  st2common/tests/unit/test_util_sandboxing.py
Labels: python3

#4653 Add tests for render_final_params and local and remote script runner command construction
  st2actions/tests/unit/test_paramiko_remote_script_runner.py
  st2common/tests/unit/test_param_utils.py
  st2common/tests/unit/test_shell_action_system_model.py
Labels: tests

#4667 Remove policy-delayed status to avoid bouncing between delayed statuses
  CHANGELOG.rst
  contrib/runners/mistral_v2/mistral_v2/callback.py
  st2actions/st2actions/cmd/scheduler.py
  st2actions/st2actions/policies/concurrency.py
  st2actions/st2actions/policies/concurrency_by_attr.py
  st2actions/st2actions/scheduler/entrypoint.py
  st2actions/st2actions/scheduler/handler.py
  st2actions/tests/unit/policies/test_concurrency.py
  st2actions/tests/unit/test_queue_consumers.py
  st2actions/tests/unit/test_scheduler.py
  st2common/bin/migrations/v3.1/st2-cleanup-policy-delayed.py
  st2common/st2common/constants/action.py
  st2common/st2common/models/db/execution_queue.py
  st2common/st2common/openapi.yaml
  st2common/st2common/policies/concurrency.py
  st2common/st2common/services/policies.py
  st2common/st2common/services/workflows.py
Labels: bug, scheduler

#4675 Fix a possible shell command injection in the linux.service action
  CHANGELOG.rst
  contrib/linux/actions/service.py
  contrib/linux/actions/service.yaml
Labels: bug, security

#4683 Update st2rc.sample.ini
  conf/st2rc.sample.ini
Labels: documentation

#4685 Update out of date st2client/README.rst and add some additional info
  st2client/README.rst
Labels: CLI, component:st2client, documentation

#4686 Replace sseclient with sseclient-py (fix hanging of "st2 execution tail" command)
  CHANGELOG.rst
  Makefile
  fixed-requirements.txt
  requirements.txt
  st2client/in-requirements.txt
  st2client/requirements.txt
  st2client/st2client/models/core.py
  st2client/tests/unit/test_models.py
Labels: CLI, component:st2client, external dependency

#4693 Update st2-self-check so it prints out output of st2 run on test failure
  st2common/bin/st2-self-check
Labels: tests

#4690 Limit database index field names to 65 characters
  CHANGELOG.rst
  st2common/st2common/models/db/execution_queue.py
  st2common/tests/unit/test_db.py
  st2tests/st2tests/base.py
Labels: database, enhancement, mongodb

#4689 Update the requests library version to latest (2.22.0) in requirements
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2client/requirements.txt
  st2common/requirements.txt
Labels: external dependency
