Repository StackStorm/st2, pull requests merged in 2020-09, with the labels that each got.

#5032 Update ST2 CircleCI and Travis to use mongodb 4.0 instead of 3.4
  .circleci/config.yml
  .travis.yml
Labels: size/S

#5034 remove py3-unit-nightly from Travis runs
  Makefile
  scripts/travis/install-requirements.sh
Labels: infrastructure: ci/cd, size/S

#5037 Add python warning if install a pack that only supports python 2
  CHANGELOG.rst
  contrib/packs/actions/get_pack_warnings.yaml
  contrib/packs/actions/pack_mgmt/get_pack_warnings.py
  contrib/packs/actions/workflows/install.yaml
  contrib/packs/tests/test_get_pack_warnings.py
  st2client/st2client/commands/pack.py
  st2common/st2common/util/pack.py
  st2common/st2common/util/pack_management.py
  st2common/tests/unit/test_util_pack.py
Labels: size/L

#5043 Add warning messages to logs if StackStorm running with python 2
  CHANGELOG.rst
  st2common/st2common/constants/error_messages.py
  st2common/st2common/service_setup.py
Labels: feature, size/S

#5048 Update the st2 API validation on RBAC configuration
  CHANGELOG.rst
  contrib/runners/inquirer_runner/inquirer_runner/runner.yaml
  st2api/st2api/validation.py
  st2api/tests/unit/test_validation_utils.py
  st2tests/st2tests/fixtures/generic/runners/inquirer.yaml
Labels: size/M

#5044 Add deprecation warning on st2ctl start if st2/python is python 2.x
  CHANGELOG.rst
  st2common/bin/st2ctl
Labels: enhancement, feature, size/S

#4983 Remove authentication headers from webhook payloads
  CHANGELOG.rst
  st2api/st2api/controllers/v1/webhooks.py
  st2api/tests/unit/controllers/v1/test_webhooks.py
Labels: bug, security, size/M
