Repository StackStorm/st2, pull requests merged in 2020-05, with the labels that each got.

#4929 Pinning pip to 20.0.2 to fix build issues introduced in pip 20.1
  Makefile
  st2common/bin/st2-run-pack-tests
  st2common/tests/unit/test_dist_utils.py
Labels: bug, size/S

#4933 #4932 - Fixes for field escaping in orquesta workflows
  CHANGELOG.rst
  Makefile
  contrib/examples/actions/orquesta-test-field-escaping.yaml
  contrib/examples/actions/python-mock-core-remote.py
  contrib/examples/actions/python-mock-core-remote.yaml
  contrib/examples/actions/workflows/tests/orquesta-test-field-escaping.yaml
  st2common/st2common/models/db/workflow.py
  st2tests/integration/orquesta/test_wiring.py
Labels: bug, regression, size/L

#4915 Add st2-generate-schemas to autogen schemas for the content models
  CHANGELOG.rst
  Makefile
  contrib/schemas/action.json
  contrib/schemas/alias.json
  contrib/schemas/pack.json
  contrib/schemas/policy.json
  contrib/schemas/rule.json
  st2common/bin/st2-generate-schemas
  st2common/st2common/models/api/action.py
  st2common/st2common/models/api/rule.py
Labels: size/XXL

#4942 Proposal: Add @winem to the StackStorm Contributors [skip ci]
  OWNERS.md
Labels: TSC:voting, proposal, size/XS

#4947 fix netstat action in linux pack
  CHANGELOG.rst
  contrib/linux/actions/netstat.yaml
  contrib/linux/actions/netstat_grep.yaml
  contrib/runners/orquesta_runner/orquesta_functions/st2kv.py
  st2common/st2common/util/monkey_patch.py
  st2common/tests/unit/test_dist_utils.py
Labels: size/S

#4949 Fix typos in support request template
  .github/ISSUE_TEMPLATE/support_request.md
Labels: size/XS

#4957 Pin pip consistently in one place across the targets, fix st2docs build
  .travis.yml
  Makefile
Labels: enhancement, maintenance, refactor, size/S

#4959 Fix empty with items list resulting in parent workflow stuck in running
  CHANGELOG.rst
  contrib/examples/actions/orquesta-test-subworkflow-empty-with-items.yaml
  contrib/examples/actions/workflows/tests/orquesta-test-subworkflow-empty-with-items.yaml
  contrib/runners/orquesta_runner/tests/unit/test_with_items.py
  st2common/st2common/services/workflows.py
  st2tests/integration/orquesta/test_wiring_with_items.py
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/with-items-empty-parent.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/with-items-empty.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/with-items-empty-parent.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/with-items-empty.yaml
Labels: size/L
