Repository StackStorm/st2, pull requests merged in 2020-01, with the labels that each got.

#4848 Notify #development channel in community Slack about TravisCI failures
  .travis.yml
Labels: enhancement, size/XS

#4847 Fix to st2client install check
  fixed-requirements.txt
  requirements.txt
  st2client/in-requirements.txt
  st2client/requirements.txt
Labels: size/XS

#4849 remove scrutinizer configs and references
  .scrutinizer.yml
  CHANGELOG.rst
  README.md
Labels: size/L

#4616 Implement rerun from specific task(s)
  contrib/examples/actions/orquesta-test-rerun.yaml
  contrib/examples/actions/workflows/tests/orquesta-test-rerun.yaml
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/orquesta_runner/orquesta_runner.py
  contrib/runners/orquesta_runner/requirements.txt
  contrib/runners/orquesta_runner/tests/unit/test_rerun.py
  requirements.txt
  st2api/st2api/controllers/v1/actionexecutions.py
  st2api/tests/unit/controllers/v1/test_executions.py
  st2client/st2client/models/core.py
  st2client/tests/unit/test_client_executions.py
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2common/st2common/exceptions/workflow.py
  st2common/st2common/services/workflows.py
  st2common/tests/unit/services/test_workflow_rerun.py
  st2tests/integration/orquesta/test_wiring_rerun.py
  st2tests/st2tests/base.py
Labels: runners, size/XXL, workflows: orquesta

#4845 Fix the amqp connection for WorkflowExecutionHandler to pass the SSL params
  CHANGELOG.rst
  st2actions/st2actions/workflows/workflows.py
Labels: bug, rabbitmq, size/XS

#4850 Update orquesta requirement to version with fix to task rerun
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/S

#4841 New example for an Orquesta workflow
  contrib/examples/actions/orquesta-ask-multiple-parameters.yaml
  contrib/examples/actions/workflows/orquesta-ask-multiple-parameters.yaml
Labels: enhancement, size/M, workflows: orquesta
