Repository StackStorm/st2, pull requests merged in 2020-03, with the labels that each got.

#4891 HA: comment out Action Runner config virtualenv_opts = --always-copy
  conf/HA/st2.conf.sample
Labels: bug, size/XS

#4877 exception was being thrown on logging output
  st2actions/st2actions/workflows/workflows.py
Labels: size/XS

#4892 Rollback workflow DB change on errors field
  contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
  st2common/st2common/models/db/workflow.py
  st2common/st2common/util/mongoescape.py
  st2common/tests/unit/test_mongoescape.py
Labels: size/L
