Repository StackStorm/st2, pull requests merged in 2020-06, with the labels that each got.

#4962 Update the LF Charter to the Correct One
  GOVERNANCE.md
Labels: TSC:voting, size/XS

#4965 Add Github "Sponsor" Button
  .github/FUNDING.yml
Labels: feature, size/XS

#4966 remove deprecated ssl and duplicate proxy host header
  CHANGELOG.rst
  conf/HA/nginx/st2.conf.blueprint.sample
  conf/HA/nginx/st2.conf.controller.sample
Labels: bug, size/XS

#4971 Propose adding @amanda11 to the StackStorm Contributors
  OWNERS.md
Labels: TSC:voting, size/XS

#4974 Fixed exception during SSH runner socket cleanup
  CHANGELOG.rst
  st2actions/tests/unit/test_paramiko_ssh.py
  st2common/st2common/runners/paramiko_ssh.py
Labels: bug, size/M
