Repository StackStorm/st2, pull requests merged in 2020-02, with the labels that each got.

#4852 Add el8 rpm package builds to CircleCI
  .circleci/config.yml
Labels: infrastructure: ci/cd, size/XS

#4856 Initial project OWNERS and GOVERNANCE under the LinuxFoundation
  .github/CODEOWNERS
  GOVERNANCE.md
  OWNERS.md
Labels: RFR, feature, size/L

#4869 Fix master builds
  .gitignore
  .travis.yml
  Makefile
  fixed-requirements.txt
  requirements.txt
  scripts/travis/add-itest-user-key.sh
  scripts/travis/prepare-integration.sh
  scripts/travis/setup-mistral.sh
  st2actions/requirements.txt
  st2client/requirements.txt
  st2common/requirements.txt
  st2debug/requirements.txt
Labels: size/M

#4871 Add changelog entries for #4869
  CHANGELOG.rst
Labels: size/XS

#4863 Switch Travis from Precise to Xenial infra
  .travis.yml
  Makefile
  scripts/travis/install-requirements.sh
  scripts/travis/permissions-workaround.sh
  scripts/travis/rabbitmq.config
  st2common/tests/integration/test_rabbitmq_ssl_listener.py
  tox.ini
Labels: enhancement, infrastructure: ci/cd, size/L

#4854 Convert escaped dict fields in workflow db models to dict fields
  CHANGELOG.rst
  st2common/st2common/models/db/workflow.py
Labels: enhancement, performance, size/S

#4875 Rollback field changes on workflow and task execution collection
  contrib/examples/actions/orquesta-mock-create-vm.yaml
  contrib/examples/actions/python-mock-create-vm.py
  contrib/examples/actions/python-mock-create-vm.yaml
  contrib/examples/actions/workflows/orquesta-mock-create-vm.yaml
  scripts/travis/prepare-integration.sh
  st2common/st2common/models/db/workflow.py
  st2tests/integration/orquesta/test_performance.py
Labels: size/M
