Repository StackStorm/st2, pull requests merged in 2020-04, with the labels that each got.

#4895 Various requirements fixups
  .travis.yml
  CHANGELOG.rst
  Makefile
  fixed-requirements.txt
  requirements.txt
  scripts/dist_utils.py
  scripts/fixate-requirements.py
  st2actions/requirements.txt
  st2api/in-requirements.txt
  st2api/requirements.txt
  test-requirements.txt
Labels: maintenance, performance, size/L

#4898 Refactor evaluation of inbound criteria of join task in orquesta workflow
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/S

#4899 Deploy EL8 packages as well
  .circleci/config.yml
Labels: complexity:easy, deployment, size/XS

#4897 Don't test or build Ubuntu 14 packages
  .circleci/config.yml
  CHANGELOG.rst
Labels: complexity:easy, deployment, enhancement, infrastructure: ci/cd, size/XS

#4881 Close proxycommand socket when its not needed anymore and resolve ssh zombies
  CHANGELOG.rst
  st2actions/tests/unit/test_paramiko_ssh.py
  st2common/st2common/runners/paramiko_ssh.py
Labels: bug, size/S, status:missing tests

#4902 Improve test failure directions
  Makefile
Labels: enhancement, infrastructure: ci/cd, size/L

#4903 Update orquesta to version that has the syntax fix for with items task
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/S, workflows: orquesta

#4861 #4804 Handle action parameters of type array correctly
  CHANGELOG.rst
  st2common/st2common/util/action_db.py
  st2common/tests/unit/test_action_db_utils.py
Labels: size/M

#4901 Fixes: #4890 to support new ssh key types
  .travis.yml
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2common/requirements.txt
Labels: external dependency, size/XS

#4874 #4828 - fix tag filter when querying actions
  CHANGELOG.rst
  st2api/st2api/controllers/v1/actions.py
Labels: bug, size/XS

#4907 Update orquesta to version that has the vars eval fix for ctx() dict methods
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/S

#4886 Make scheduling timeout constant to be a configurable option
  CHANGELOG.rst
  conf/st2.conf.sample
  st2actions/st2actions/scheduler/config.py
  st2actions/st2actions/scheduler/handler.py
  st2tests/st2tests/config.py
Labels: enhancement, size/S

#4909 Update orquesta to version with array of dicts fix for YAQL functions
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2common/st2common/expressions/functions/data.py
  st2common/st2common/util/db.py
Labels: size/S

#4910 Pin orquesta to v1.1.0 for the st2 v3.2 release
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/S

#4919 Fix typo in the supported API filters when filtering packs
  CHANGELOG.rst
  st2api/st2api/controllers/v1/actions.py
  st2api/tests/unit/controllers/v1/test_actions.py
Labels: API, bug, service: api, size/M

#4917 Remove deprecated 'ssl on' nginx config
  CHANGELOG.rst
  conf/nginx/st2.conf
Labels: enhancement, size/XS

#4921 Update orquesta version with fix for task retry
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/S

#4925 Run make .requirements to update st2actions/requirements.txt after ch…
  st2actions/requirements.txt
Labels: bug, size/XS
