Repository StackStorm/st2, pull requests merged in 2020-08, with the labels that each got.

#5010 Fix stable st2docs builds (v3.2)
  .travis.yml
  Makefile
  contrib/runners/orquesta_runner/orquesta_functions/st2kv.py
  st2common/st2common/util/monkey_patch.py
  st2common/tests/unit/test_dist_utils.py
Labels: bug, size/M

#5013 better expose default creds for devs
  CHANGELOG.rst
  dev_docs/Troubleshooting_Guide.rst
  tools/launchdev.sh
Labels: documentation, enhancement, size/S

#4981 ST2api Log Fix So That Querying a Non-Existent Key in the Datastore Will Not Print Traceback
  CHANGELOG.rst
  st2common/st2common/exceptions/keyvalue.py
  st2common/st2common/persistence/keyvalue.py
  st2common/st2common/router.py
Labels: enhancement, size/S

#4993 Fix bytes -> str handling in linux.dig action
  CHANGELOG.rst
  contrib/linux/actions/dig.py
  contrib/linux/tests/test_action_dig.py
Labels: bug, python3, size/M, status:missing tests

#5027 Merge changed sections in the CHANGELOG
  CHANGELOG.rst
Labels: size/XS

#5018 Promote Amanda McGuinness (@amanda11) to the StackStorm TSC Maintainers
  OWNERS.md
Labels: TSC:voting, proposal, size/XS

#5019 Proposal: Invite @Contributors to StackStorm Github special group
  OWNERS.md
Labels: TSC:voting, proposal, size/XS, status:under discussion

#5022 Propose adding @Sheshagiri to the StackStorm Contributors
  OWNERS.md
Labels: TSC:voting, size/XS

#5025 Add AJ Jonen (@guzzijones) to the list of StackStorm Contributors
  OWNERS.md
Labels: TSC:voting, proposal, size/XS

#5028 Remove LindsayHill from TSC
  OWNERS.md
Labels: size/XS
