Repository StackStorm/st2, pull requests merged in 2020-12, with the labels that each got.

#5095 Update cryptography version to 3.2
  CHANGELOG.rst
  contrib/runners/python_runner/tests/unit/test_pythonrunner.py
  fixed-requirements.txt
  requirements.txt
  st2client/requirements.txt
  st2common/requirements.txt
Labels: cryptography, external dependency, maintenance, size/M

#5101 ADOPTERS.md: Reference Fastly success story with the StackStorm Network Automation
  ADOPTERS.md
Labels: documentation, enhancement, size/XS

#5104 Update __init__.py
  CHANGELOG.rst
  st2tests/st2tests/__init__.py
Labels: enhancement, size/XS

#5105 Fix chardet as fix requests
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2actions/in-requirements.txt
  st2actions/requirements.txt
  st2api/in-requirements.txt
  st2auth/in-requirements.txt
  st2client/in-requirements.txt
  st2client/requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2debug/in-requirements.txt
  st2debug/requirements.txt
  st2exporter/in-requirements.txt
  st2reactor/in-requirements.txt
  st2stream/in-requirements.txt
  st2tests/in-requirements.txt
Labels: bug, size/M

#5090 Remove Python 2.7 from tests and builds
  .circleci/config.yml
  .travis.yml
  CHANGELOG.rst
  Makefile
  st2actions/bin/st2actionrunner
  st2actions/bin/st2notifier
  st2actions/bin/st2resultstracker
  st2actions/bin/st2scheduler
  st2actions/bin/st2workflowengine
  st2api/bin/st2api
  st2auth/bin/st2auth
  st2client/Makefile
  st2client/setup.py
  st2common/bin/paramiko_ssh_evenlets_tester.py
  st2common/bin/st2-bootstrap-rmq
  st2common/bin/st2-cleanup-db
  st2common/bin/st2-generate-schemas
  st2common/bin/st2-register-content
  st2common/bin/st2-validate-pack-config
  st2debug/bin/st2-submit-debug-info
  st2exporter/bin/st2exporter
  st2reactor/bin/st2-rule-tester
  st2reactor/bin/st2-trigger-refire
  st2reactor/bin/st2garbagecollector
  st2reactor/bin/st2rulesengine
  st2reactor/bin/st2sensorcontainer
  st2reactor/bin/st2timersengine
  st2stream/bin/st2stream
  tools/st2-setup-examples
  tools/st2-setup-tests
Labels: WIP, component:st2auth, component:st2client, enhancement, python3, size/L

#5106 Decode pack files as utf-8 instead of ascii
  CHANGELOG.rst
  st2common/st2common/content/loader.py
Labels: API, bug, packs, python3, regression, size/XS

#5099 Improve python2 pack warning when running on Python 3 environment
  CHANGELOG.rst
  st2common/st2common/util/pack.py
Labels: enhancement, size/S

#5107 Use io.open() when running on Python 2
  CHANGELOG.rst
  st2common/st2common/content/loader.py
Labels: bug, packs, python3, regression, size/XS

#5103 Remove st2-debug-info
  CHANGELOG.rst
  Makefile
  requirements.txt
  st2debug/MANIFEST.in
  st2debug/Makefile
  st2debug/bin/st2-submit-debug-info
  st2debug/dist_utils.py
  st2debug/in-requirements.txt
  st2debug/requirements.txt
  st2debug/setup.py
  st2debug/st2debug/__init__.py
  st2debug/st2debug/cmd/__init__.py
  st2debug/st2debug/cmd/submit_debug_info.py
  st2debug/st2debug/constants.py
  st2debug/st2debug/processors.py
  st2debug/st2debug/utils/__init__.py
  st2debug/st2debug/utils/fs.py
  st2debug/st2debug/utils/git_utils.py
  st2debug/st2debug/utils/system_info.py
  st2debug/tests/__init__.py
  st2debug/tests/fixtures/deb_pkg_list
  st2debug/tests/fixtures/proc_cpuinfo
  st2debug/tests/fixtures/proc_meminfo
  st2debug/tests/fixtures/rpm_pkg_list
  st2debug/tests/integration/__init__.py
  st2debug/tests/integration/fixtures/configs/st2.conf
  st2debug/tests/integration/fixtures/content/twilio/CHANGES.md
  st2debug/tests/integration/fixtures/content/twilio/README.md
  st2debug/tests/integration/fixtures/content/twilio/actions/send_sms.py
  st2debug/tests/integration/fixtures/content/twilio/actions/send_sms.yaml
  st2debug/tests/integration/fixtures/content/twilio/config.yaml
  st2debug/tests/integration/fixtures/content/twilio/pack.yaml
  st2debug/tests/integration/fixtures/content/twilio/requirements.txt
  st2debug/tests/integration/fixtures/logs/st2api.log
  st2debug/tests/integration/fixtures/logs/st2sensorcontainer.log
  st2debug/tests/integration/test_submit_debug_info.py
  st2debug/tests/unit/__init__.py
  st2debug/tests/unit/test_system_info.py
  st2tests/Makefile
  tox.ini
Labels: refactor
