Repository StackStorm/st2, pull requests merged in 2020-07, with the labels that each got.

#4984 Remove EL6 support
  .circleci/config.yml
  CHANGELOG.rst
  Makefile
  st2actions/Makefile
  st2actions/bin/runners.sh
  st2api/Makefile
  st2auth/Makefile
  st2client/Makefile
  st2common/bin/st2ctl
  st2debug/Makefile
  st2reactor/Makefile
  st2stream/Makefile
  st2tests/Makefile
Labels: breaking change, enhancement, size/L

#4985 Update progress of workflow execution to the output stream
  contrib/runners/orquesta_runner/orquesta_runner/orquesta_runner.py
  contrib/runners/orquesta_runner/tests/unit/test_basic.py
  contrib/runners/orquesta_runner/tests/unit/test_context.py
  st2actions/st2actions/workflows/workflows.py
  st2common/st2common/services/action.py
  st2common/st2common/services/workflows.py
  st2common/tests/unit/services/test_workflow.py
  st2common/tests/unit/services/test_workflow_identify_orphans.py
  st2tests/st2tests/base.py
Labels: size/L

#4991 update sensor partitioner error message
  CHANGELOG.rst
  st2reactor/st2reactor/container/manager.py
Labels: size/XS

#4976 Fixes: #4875 monkeypatch st2 sensor earlier
  CHANGELOG.rst
  st2actions/st2actions/cmd/actionrunner.py
  st2actions/st2actions/cmd/st2notifier.py
  st2actions/st2actions/cmd/st2resultstracker.py
  st2auth/st2auth/cmd/api.py
  st2common/bin/paramiko_ssh_evenlets_tester.py
  st2exporter/st2exporter/cmd/st2exporter_starter.py
  st2reactor/st2reactor/cmd/garbagecollector.py
  st2reactor/st2reactor/cmd/rulesengine.py
  st2reactor/st2reactor/cmd/sensormanager.py
  st2reactor/st2reactor/cmd/timersengine.py
  st2reactor/st2reactor/container/sensor_wrapper.py
  st2reactor/tests/unit/test_sensor_wrapper.py
Labels: bug, size/M

#4996 Update Adopters with HPE and Adobe
  ADOPTERS.md
Labels: documentation, size/XS

#4914 Feature request #4715: configurable ssh connect timeout
  CHANGELOG.rst
  conf/st2.conf.sample
  st2actions/tests/unit/test_parallel_ssh.py
  st2actions/tests/unit/test_paramiko_ssh.py
  st2common/st2common/config.py
  st2common/st2common/runners/paramiko_ssh.py
Labels: enhancement, feature, size/M, status:missing tests

#4952 Rules Engine Logging error
  CHANGELOG.rst
  st2common/st2common/models/db/stormbase.py
  st2common/tests/unit/test_db_base.py
  st2common/tests/unit/test_logger.py
Labels: bug, size/L

#5002 Use upstream codecov instead of our own fork
  CHANGELOG.rst
  scripts/travis/submit-codecov-coverage.sh
Labels: bug, size/XS

#4997 Pin dnspython pip dependency due to regression in v2.0.0
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: bug, size/XS

#5005 Fixed bash issue with travis codecov submissions not working
  scripts/travis/submit-codecov-coverage.sh
Labels: size/XS

#4994 Remove inactive Contributors
  OWNERS.md
Labels: TSC:voting, size/XS

#4992 Fix st2.action.file_writen typo
  CHANGELOG.rst
  st2common/st2common/constants/triggers.py
Labels: breaking change, bug, size/XS

#4978 add mongo note to changelog
  CHANGELOG.rst
Labels: size/S
