Repository StackStorm/st2, pull requests merged in 2020-11, with the labels that each got.

#5077 Remove py2.7 from the README badges
  .circleci/config.yml
  README.md
Labels: size/XS

#5082 Adding ldap support as auth backend
  CHANGELOG.rst
  conf/st2.conf.sample
  requirements.txt
  st2auth/in-requirements.txt
  st2auth/requirements.txt
Labels: feature, size/S

#5042 Fix sse and nginx buffering
  CHANGELOG.rst
  conf/nginx/st2.conf
  st2client/st2client/base.py
  st2client/st2client/commands/action.py
  st2client/st2client/commands/pack.py
  st2client/st2client/models/core.py
  st2common/st2common/openapi.yaml
  st2common/st2common/openapi.yaml.j2
  st2common/st2common/stream/listener.py
  st2common/tests/unit/test_stream_generator.py
  st2stream/st2stream/controllers/v1/executions.py
  st2stream/st2stream/controllers/v1/stream.py
Labels: size/L

#5084 Add option to override Pack install timeout
  CHANGELOG.rst
  contrib/packs/actions/install.meta.yaml
  contrib/packs/actions/setup_virtualenv.yaml
  contrib/packs/actions/workflows/install.yaml
Labels: enhancement, size/S

#5091 ticket #5078 fix: Resolves issue where st2stream crashes with a max depth error when connecting to a mongodb via SSL
  CHANGELOG.rst
  st2stream/st2stream/cmd/api.py
Labels: bug, size/XS

#5086 Rbac integration
  CHANGELOG.rst
  requirements.txt
  st2api/st2api/validation.py
  st2api/tests/unit/test_validation_utils.py
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: RBAC, size/S

#5092 remove obsolete check-licence
  CHANGELOG.rst
  st2common/bin/st2-check-license
  st2common/setup.py
Labels: enhancement, refactor, size/M
