Repository StackStorm/st2, pull requests merged in 2021-12, with the labels that each got.

#5450 Add Khushboo Bhatia (@khushboobhatia01) as a Contributor
  OWNERS.md
Labels: size/XS, TSC:voting

#5452 Add Rick Kauffman (@xod442) as a Contributor
  OWNERS.md
Labels: size/XS, TSC:voting

#5459 Add status changed by user info to context
  CHANGELOG.rst
  contrib/runners/orquesta_runner/tests/unit/test_cancel.py
  contrib/runners/orquesta_runner/tests/unit/test_pause_and_resume.py
  st2common/st2common/services/action.py
Labels: size/M

#5396 Deregister services from service registry on shutdown
  CHANGELOG.rst
  st2actions/st2actions/cmd/actionrunner.py
  st2actions/st2actions/cmd/scheduler.py
  st2actions/st2actions/cmd/st2notifier.py
  st2actions/st2actions/cmd/workflow_engine.py
  st2api/st2api/cmd/api.py
  st2auth/st2auth/cmd/api.py
  st2common/st2common/service_setup.py
  st2common/st2common/services/coordination.py
  st2common/tests/unit/test_service_setup.py
  st2reactor/st2reactor/cmd/garbagecollector.py
  st2reactor/st2reactor/cmd/rulesengine.py
  st2reactor/st2reactor/cmd/sensormanager.py
  st2reactor/st2reactor/cmd/timersengine.py
  st2stream/st2stream/cmd/api.py
Labels: enhancement, size/L

#5484 Fix etcd lock error
  CHANGELOG.rst
  st2common/st2common/services/executions.py
Labels: size/S

#5489 Revert "Add status changed by user info to context"
  CHANGELOG.rst
  contrib/runners/orquesta_runner/tests/unit/test_cancel.py
  contrib/runners/orquesta_runner/tests/unit/test_pause_and_resume.py
  st2common/st2common/services/action.py
Labels: bug, regression, size/M

#5487 Fix st2-self-check script reporting success on failed runs
  CHANGELOG.rst
  st2common/bin/st2-self-check
Labels: bug, size/XS

#5354 Implementation of RBAC for KeyValuePair
  CHANGELOG.rst
  st2api/st2api/controllers/v1/keyvalue.py
  st2api/tests/unit/controllers/v1/test_kvps.py
  st2client/st2client/commands/resource.py
  st2common/st2common/rbac/backends/base.py
  st2common/st2common/rbac/backends/noop.py
  st2common/st2common/services/keyvalues.py
  st2common/tests/unit/services/test_keyvalue.py
Labels: feature, security, RBAC, size/XL

#5498 Add CHANGELOG for action clone feature
  CHANGELOG.rst
Labels: size/S

#5517 update test-requirements.txt to match fixed-requirements.txt
  .github/workflows/ci.yaml
  .github/workflows/microbenchmarks.yaml
  .github/workflows/orquesta-integration-tests.yaml
  fixed-requirements.txt
  test-requirements.txt
Labels: external dependency, size/M

#5524 install wheel to fix check-python-packages-nightly CI
  Makefile
Labels: size/XS, infrastructure: ci/cd, maintenance
