Repository StackStorm/st2, pull requests merged in 2021-01, with the labels that each got.

#5100 Remove --python3 option
  CHANGELOG.rst
  conf/st2.conf.sample
  contrib/packs/actions/download.yaml
  contrib/packs/actions/install.meta.yaml
  contrib/packs/actions/pack_mgmt/download.py
  contrib/packs/actions/pack_mgmt/setup_virtualenv.py
  contrib/packs/actions/setup_virtualenv.yaml
  contrib/packs/actions/workflows/install.yaml
  contrib/packs/tests/test_action_download.py
  st2api/st2api/controllers/v1/packs.py
  st2client/st2client/commands/pack.py
  st2client/st2client/models/core.py
  st2common/st2common/cmd/download_pack.py
  st2common/st2common/cmd/install_pack.py
  st2common/st2common/cmd/setup_pack_virtualenv.py
  st2common/st2common/config.py
  st2common/st2common/constants/error_messages.py
  st2common/st2common/constants/pack.py
  st2common/st2common/openapi.yaml
  st2common/st2common/openapi.yaml.j2
  st2common/st2common/util/pack_management.py
  st2common/st2common/util/sandboxing.py
  st2common/st2common/util/virtualenvs.py
  st2common/tests/unit/test_util_sandboxing.py
  st2common/tests/unit/test_virtualenvs.py
  st2reactor/st2reactor/container/process_container.py
  tools/config_gen.py
Labels: size/L

#5111 Slack notification on failed Github Action executions on the master branch
  .github/workflows/ci.yaml
Labels: infrastructure: ci/cd, size/S

#5118 Keep enough Travis configuration to run integration tests
  .github/workflows/ci.yaml
  .gitignore
  .travis.yml
  CHANGELOG.rst
  Makefile
  scripts/travis/install-requirements.sh
  scripts/travis/permissions-workaround.sh
  scripts/travis/prepare-integration.sh
  scripts/travis/rabbitmq.config
  scripts/travis/submit-codecov-coverage.sh
  scripts/travis/time-command.sh
  tox.ini
Labels: infrastructure: ci/cd, size/M, tests

#5098 Convert CI to GitHub Actions
  .github/workflows/ci.yaml
  .gitignore
  .travis.yml
  CHANGELOG.rst
  Makefile
  README.md
  contrib/runners/python_runner/tests/integration/test_python_action_process_wrapper.py
  scripts/travis/add-itest-user-key.sh
  scripts/travis/install-requirements.sh
  scripts/travis/permissions-workaround.sh
  scripts/travis/prepare-integration.sh
  scripts/travis/submit-codecov-coverage.sh
  scripts/travis/time-command.sh
  st2client/tests/unit/test_util_terminal.py
  st2common/st2common/util/sandboxing.py
  st2common/st2common/util/virtualenvs.py
  st2common/tests/integration/test_rabbitmq_ssl_listener.py
  st2common/tests/unit/test_util_sandboxing.py
  tox.ini
Labels: feature, infrastructure: ci/cd, size/L

#5050 Allows GitLab SSH URLs on pack actions
  CHANGELOG.rst
  st2common/st2common/util/pack_management.py
  st2common/tests/unit/test_pack_management.py
Labels: size/S

#5108 Remove st2resultstracker from st2ctl, the development environment and the st2actions setup
  .travis.yml
  CHANGELOG.rst
  conf/HA/st2.conf.sample
  conf/logrotate.conf
  conf/st2.conf.sample
  conf/st2.dev.conf
  conf/st2.package.conf
  conf/st2.tests.conf
  conf/st2.tests1.conf
  conf/st2.tests2.conf
  st2actions/bin/st2resultstracker
  st2actions/conf/logging.resultstracker.conf
  st2actions/conf/syslog.resultstracker.conf
  st2actions/setup.py
  st2actions/st2actions/cmd/st2resultstracker.py
  st2actions/st2actions/resultstracker/__init__.py
  st2actions/st2actions/resultstracker/config.py
  st2actions/st2actions/resultstracker/resultstracker.py
  st2actions/tests/integration/test_action_state_consumer.py
  st2actions/tests/integration/test_resultstracker.py
  st2api/tests/unit/controllers/v1/test_packs.py
  st2common/bin/st2ctl
  st2common/st2common/config.py
  st2common/st2common/constants/runners.py
  st2common/st2common/query/__init__.py
  st2common/st2common/query/base.py
  st2common/st2common/runners/base.py
  st2common/st2common/util/loader.py
  st2common/tests/runners/mock_query_callback/MANIFEST.in
  st2common/tests/runners/mock_query_callback/callback/__init__.py
  st2common/tests/runners/mock_query_callback/dist_utils.py
  st2common/tests/runners/mock_query_callback/in-requirements.txt
  st2common/tests/runners/mock_query_callback/mock_query_callback/__init__.py
  st2common/tests/runners/mock_query_callback/mock_query_callback/callback.py
  st2common/tests/runners/mock_query_callback/mock_query_callback/mock_query_callback.py
  st2common/tests/runners/mock_query_callback/mock_query_callback/query.py
  st2common/tests/runners/mock_query_callback/mock_query_callback/runner.yaml
  st2common/tests/runners/mock_query_callback/query/__init__.py
  st2common/tests/runners/mock_query_callback/requirements.txt
  st2common/tests/runners/mock_query_callback/runner.yaml
  st2common/tests/runners/mock_query_callback/setup.py
  st2common/tests/unit/test_query_base.py
  st2common/tests/unit/test_runners_base.py
  st2tests/conf/st2.conf
  st2tests/st2tests/config.py
  st2tests/st2tests/fixtures/conf/st2.tests.api.audit_log_level.conf
  st2tests/st2tests/fixtures/conf/st2.tests.api.debug_log_level.conf
  st2tests/st2tests/fixtures/conf/st2.tests.api.info_log_level.conf
  st2tests/st2tests/fixtures/conf/st2.tests.api.system_debug_true.conf
  st2tests/st2tests/fixtures/conf/st2.tests.api.system_debug_true_logging_debug.conf
  st2tests/st2tests/fixtures/conf/st2.tests.conf
  st2tests/st2tests/fixtures/packs/runners/test_querymodule/__init__.py
  st2tests/st2tests/fixtures/packs/runners/test_querymodule/callback/__init__.py
  st2tests/st2tests/fixtures/packs/runners/test_querymodule/callback/test_querymodule.py
  st2tests/st2tests/fixtures/packs/runners/test_querymodule/query/__init__.py
  st2tests/st2tests/fixtures/packs/runners/test_querymodule/query/test_querymodule.py
  tools/config_gen.py
  tools/launchdev.sh
  tools/screen-configs/st2resultstracker.conf
Labels: size/XL

#5121 Tooz 2.8.0
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2actions/requirements.txt
  st2api/requirements.txt
  st2common/requirements.txt
  st2stream/requirements.txt
Labels: enhancement, size/S

#5114 Add @shital-orchestral to the list of Contributors
  OWNERS.md
Labels: TSC:voting, size/XS

#5115 Add @hnanchahal to the list of Contributors
  OWNERS.md
Labels: TSC:voting, size/XS

#5117 Update orquesta in requirements to v1.3.0
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2common/st2common/services/workflows.py
Labels: size/S

#5134 Update versions of st2tests and isort
  st2tests/st2tests/__init__.py
  test-requirements.txt
Labels: size/XS
