Repository StackStorm/st2, pull requests merged in 2021-04, with the labels that each got.

#5193 Fixed Apache range header DOS and proxy disclosure issue
  conf/nginx/st2.conf
Labels: size/S

#5211 Experiment with running tests in parallel on GHA
  .github/workflows/ci.yaml
  Makefile
  scripts/github/install-apt-packages-use-cache.sh
  scripts/github/prepare-integration.sh
  st2common/tests/integration/test_register_content_script.py
  st2reactor/tests/integration/test_sensor_container.py
  st2tests/st2tests/base.py
  test-requirements.txt
Labels: infrastructure: ci/cd, performance, size/L

#5217 Add changelog entry for https://github.com/StackStorm/st2web/pull/868.
  CHANGELOG.rst
Labels: size/S

#5219 Improve GHA workflow
  .circle/add-itest-user.sh
  .github/workflows/ci.yaml
  scripts/ci/add-itest-user-key.sh
  scripts/ci/print-versions.sh
  scripts/github/install-virtualenv.sh
  scripts/github/setup-environment.sh
Labels: infrastructure: ci/cd, size/L

#5218 Reformat more code with black
  Makefile
  st2actions/bin/st2actionrunner
  st2actions/bin/st2notifier
  st2actions/bin/st2scheduler
  st2actions/bin/st2workflowengine
  st2api/bin/st2api
  st2auth/bin/st2auth
  st2common/bin/st2-bootstrap-rmq
  st2common/bin/st2-cleanup-db
  st2common/bin/st2-generate-api-spec
  st2common/bin/st2-generate-schemas
  st2common/bin/st2-generate-symmetric-crypto-key
  st2common/bin/st2-pack-download
  st2common/bin/st2-pack-install
  st2common/bin/st2-pack-setup-virtualenv
  st2common/bin/st2-purge-executions
  st2common/bin/st2-purge-trigger-instances
  st2common/bin/st2-register-content
  st2common/bin/st2-track-result
  st2common/bin/st2-validate-api-spec
  st2common/bin/st2-validate-pack
  st2common/bin/st2-validate-pack-config
  st2exporter/bin/st2exporter
  st2reactor/bin/st2-rule-tester
  st2reactor/bin/st2-trigger-refire
  st2reactor/bin/st2garbagecollector
  st2reactor/bin/st2rulesengine
  st2reactor/bin/st2sensorcontainer
  st2reactor/bin/st2timersengine
  st2stream/bin/st2stream
Labels: size/L

#5182 Warn on service startup if a non utf-8 encoding is used
  CHANGELOG.rst
  st2common/st2common/log.py
  st2common/st2common/service_setup.py
  st2common/tests/integration/log_unicode_data.py
  st2common/tests/integration/test_logging.py
  st2common/tests/integration/test_service_setup_log_level_filtering.py
Labels: bug fix, size/XL

#5189 Correctly handle unicode characters in the URL path names and the CLI arguments (sys.argv)
  CHANGELOG.rst
  st2api/tests/unit/controllers/v1/test_actions.py
  st2api/tests/unit/controllers/v1/test_base.py
  st2client/st2client/shell.py
  st2client/st2client/utils/misc.py
  st2client/tests/unit/test_commands.py
  st2client/tests/unit/test_shell.py
  st2common/st2common/middleware/instrumentation.py
  st2common/st2common/router.py
  st2tests/st2tests/api.py
Labels: size/L

#5226 Make redis the default coordinator backend
  CHANGELOG.rst
  conf/st2.dev.conf
  fixed-requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/XS

#5228 Drop unused dependencies
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2client/in-requirements.txt
  st2client/requirements.txt
Labels: size/S

#5225 Fix decrypting pack config keys under additionalProperties
  .github/workflows/ci.yaml
  CHANGELOG.rst
  st2common/st2common/util/config_loader.py
  st2common/tests/unit/test_config_loader.py
  st2tests/st2tests/fixtures/packs/dummy_pack_schema_with_additional_properties_1/config.schema.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_schema_with_additional_properties_1/pack.yaml
Labels: enhancement, size/L

#5227 Add support to skip action notifications when executed under workflow context
  contrib/runners/action_chain_runner/tests/unit/test_actionchain_notifications.py
  contrib/runners/orquesta_runner/tests/unit/test_notify.py
  st2common/st2common/services/action.py
  st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_chain_sequential.yaml
  st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_subworkflow_default_with_notify_task.yaml
  st2tests/st2tests/fixtures/packs/action_chain_tests/actions/test_chain_sequential.yaml
  st2tests/st2tests/fixtures/packs/action_chain_tests/actions/test_subworkflow_default_with_notify_task.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/sequential-with-notify.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/subworkflow-with-notify-task.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/subworkflow-with-notify-task.yaml
Labels: size/L, workflows: orquesta

#5229 Add some more tests for run_command() function
  .github/workflows/ci.yaml
  .github/workflows/orquesta-integration-tests.yaml
  CHANGELOG.rst
  Makefile
  fixed-requirements.txt
  requirements.txt
  st2actions/tests/unit/policies/test_concurrency.py
  st2actions/tests/unit/policies/test_concurrency_by_attr.py
  st2common/tests/fixtures/print_to_stdout_stderr_sleep.sh
  st2common/tests/integration/test_service_setup_log_level_filtering.py
  st2common/tests/integration/test_util_green.py
  st2common/tests/unit/test_service_setup.py
  st2tests/requirements.txt
  st2tests/st2tests/config.py
Labels: size/XL, tests

#5233 Remove the issue template for requesting support
  .github/ISSUE_TEMPLATE/support_request.md
Labels: SUPPORT, size/S

#5234 Unify and improve config option registration code
  CHANGELOG.rst
  contrib/runners/action_chain_runner/tests/unit/test_actionchain_notifications.py
  st2actions/st2actions/config.py
  st2actions/st2actions/notifier/config.py
  st2actions/st2actions/scheduler/config.py
  st2actions/st2actions/workflows/config.py
  st2api/st2api/config.py
  st2auth/st2auth/config.py
  st2common/st2common/config.py
  st2common/st2common/content/bootstrap.py
  st2common/st2common/script_setup.py
  st2exporter/st2exporter/config.py
  st2reactor/st2reactor/garbage_collector/config.py
  st2reactor/st2reactor/rules/config.py
  st2reactor/st2reactor/timer/config.py
  st2stream/st2stream/config.py
Labels: size/L

#5212 Update requirements.txt
  CHANGELOG.rst
  contrib/runners/winrm_runner/requirements.txt
  contrib/runners/winrm_runner/winrm_runner/winrm_base.py
  fixed-requirements.txt
  requirements.txt
Labels: dependencies upgrade, size/S

#5238 Persist StackStorm service logs on integration tests failure
  .github/workflows/ci.yaml
  .github/workflows/orquesta-integration-tests.yaml
Labels: infrastructure: ci/cd, size/M, tests

#4912 Allow user to retrieve more than one resource using "st2 resource get" CLI command
  CHANGELOG.rst
  st2actions/st2actions/notifier/config.py
  st2client/st2client/commands/action.py
  st2client/st2client/commands/inquiry.py
  st2client/st2client/commands/keyvalue.py
  st2client/st2client/commands/resource.py
  st2client/st2client/commands/rule_enforcement.py
  st2client/st2client/commands/trace.py
  st2client/st2client/commands/triggerinstance.py
  st2client/st2client/models/reactor.py
  st2client/tests/base.py
  st2client/tests/unit/test_commands.py
  st2client/tests/unit/test_inquiry.py
  st2client/tests/unit/test_shell.py
  st2exporter/st2exporter/config.py
  st2reactor/st2reactor/garbage_collector/config.py
  st2reactor/st2reactor/rules/config.py
Labels: CLI, size/L

#5177 Python3.8 on Ubuntu 20.04 (requiring MongoDB 4.4)
  .github/workflows/ci.yaml
  .github/workflows/orquesta-integration-tests.yaml
  .pre-commit-config.yaml
  CHANGELOG.rst
  Makefile
  conf/st2.conf.sample
  contrib/linux/actions/service.py
  contrib/runners/python_runner/tests/integration/test_pythonrunner_behavior.py
  fixed-requirements.txt
  requirements.txt
  st2actions/tests/unit/test_scheduler.py
  st2api/st2api/controllers/v1/packs.py
  st2api/tests/unit/controllers/v1/test_executions_auth.py
  st2api/tests/unit/controllers/v1/test_packs.py
  st2client/in-requirements.txt
  st2client/requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2common/st2common/config.py
  st2common/st2common/models/db/__init__.py
  st2common/st2common/service_setup.py
  st2common/st2common/util/keyvalue.py
  st2common/st2common/util/pack_management.py
  st2common/st2common/util/service.py
  st2common/tests/integration/test_logging.py
  st2common/tests/integration/test_service_setup_log_level_filtering.py
  st2common/tests/unit/services/test_workflow_service_retries.py
  st2common/tests/unit/test_content_loader.py
  st2common/tests/unit/test_db.py
  st2reactor/st2reactor/container/sensor_wrapper.py
  st2reactor/tests/unit/test_sensor_wrapper.py
  st2stream/tests/unit/controllers/v1/test_stream.py
  st2stream/tests/unit/controllers/v1/test_stream_execution_output.py
  st2tests/st2tests/base.py
  tox.ini
Labels: OS support, deployment, feature, mongodb, size/XL

#5237 Update more dependencies to various stable versions
  .github/workflows/orquesta-integration-tests.yaml
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2actions/requirements.txt
  st2api/requirements.txt
  st2client/requirements.txt
  st2common/requirements.txt
  st2common/tests/integration/test_rabbitmq_ssl_listener.py
  st2exporter/requirements.txt
  st2reactor/requirements.txt
  st2stream/requirements.txt
  st2tests/requirements.txt
  test-requirements.txt
Labels: dependencies upgrade, external dependency, size/M

#5241 Add support for compressing payloads sent over the message bus
  .github/workflows/microbenchmarks.yaml
  .github/workflows/orquesta-integration-tests.yaml
  .gitignore
  CHANGELOG.rst
  Makefile
  conf/st2.conf.sample
  scripts/github/configure-rabbitmq.sh
  st2api/st2api/cmd/api.py
  st2auth/st2auth/cmd/api.py
  st2common/benchmarks/micro/common.py
  st2common/benchmarks/micro/test_fast_deepcopy.py
  st2common/benchmarks/micro/test_json_serialization_and_deserialization.py
  st2common/benchmarks/micro/test_mongo_escape_and_unescape.py
  st2common/benchmarks/micro/test_mongo_field_types.py
  st2common/benchmarks/micro/test_mongo_transport_compression.py
  st2common/benchmarks/micro/test_publisher_compression.py
  st2common/st2common/config.py
  st2common/st2common/transport/publishers.py
  st2common/tests/unit/test_transport.py
  st2stream/st2stream/cmd/api.py
  test-requirements.txt
  tools/config_gen.py
Labels: compression, rabbitmq, size/XL

#5240 Stop hang when use mongo SSL
  .github/workflows/microbenchmarks.yaml
  CHANGELOG.rst
  st2stream/st2stream/app.py
  st2stream/st2stream/wsgi.py
Labels: bug, eventlet monkey patching, size/S

#5242 Proposal: Promote @nmaludy to Senior Maintainers
  OWNERS.md
Labels: TSC:voting, size/XS
