Repository StackStorm/st2, pull requests merged in 2021-05, with the labels that each got.

#5251 Fix overlapping include field values for compatibility with Mongo DB 4.4
  st2api/st2api/controllers/resource.py
  st2api/tests/unit/controllers/v1/test_executions.py
Labels: mongodb, mongodb 4.4, size/S

#5129 #5128 Add reference to api_key usage in sample
  conf/st2rc.sample.ini
Labels: size/XS

#5252 Upgrade various deps to latest versions
  fixed-requirements.txt
  requirements.txt
  st2actions/requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  test-requirements.txt
Labels: dependencies upgrade, external dependency, size/M

#5255 Add migration script for migrating old execution field data to the new format
  .github/workflows/ci.yaml
  .github/workflows/microbenchmarks.yaml
  .github/workflows/orquesta-integration-tests.yaml
  CHANGELOG.rst
  scripts/github/install-apt-packages-use-cache.sh
  st2common/bin/migrations/v3.5/__init__.py
  st2common/bin/migrations/v3.5/st2-migrate-db-dict-field-values
  st2common/bin/migrations/v3.5/st2_migrate_db_dict_field_values.py
  st2common/st2common/constants/triggers.py
  st2common/tests/unit/migrations/test_v35_migrate_db_dict_field_values.py
Labels: external dependency, migrations, mongodb, performance, size/L

#5263 Remove duplicate proxy_set_header in nginx conf
  CHANGELOG.rst
  conf/nginx/st2.conf
Labels: size/XS

#5262 Add redis configuration to st2.package.conf
  conf/st2.package.conf
Labels: size/XS

#5269 Update orquesta to v1.4.0
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/S

#5268 Clean up unused methods in concurrency policies
  CHANGELOG.rst
  st2actions/st2actions/policies/concurrency.py
  st2actions/st2actions/policies/concurrency_by_attr.py
  st2common/st2common/policies/base.py
Labels: size/M

#5250 Secret masking in output_schema feature is added
  CHANGELOG.rst
  contrib/runners/orquesta_runner/tests/unit/test_data_flow.py
  st2actions/tests/unit/test_output_schema.py
  st2api/st2api/controllers/v1/actionexecutions.py
  st2api/tests/unit/controllers/v1/test_executions.py
  st2api/tests/unit/controllers/v1/test_packs.py
  st2common/st2common/models/db/execution.py
  st2common/st2common/util/output_schema.py
  st2common/tests/integration/test_register_content_script.py
  st2common/tests/unit/test_db_execution.py
  st2common/tests/unit/test_util_output_schema.py
  st2tests/st2tests/fixtures/packs/dummy_pack_1/actions/my_http_action.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_1/actions/my_py_action.py
  st2tests/st2tests/fixtures/packs/dummy_pack_1/actions/my_py_action.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/data-flow.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/py-secret-output.py
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/py-secret-output.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/data-flow.yaml
Labels: size/XL

#5267 Orjson serialize set to list
  Makefile
  st2common/benchmarks/micro/test_json_serialization_and_deserialization.py
  st2common/st2common/fields.py
  st2common/tests/unit/test_db_fields.py
Labels: bug, mongodb, size/M
