Repository StackStorm/st2, pull requests merged in 2021-03, with the labels that each got.

#5165 [BUGFIX] Use pip 20.0.2 to build virtualenvs
  fixed-requirements.txt
  test-requirements.txt
Labels: size/XS

#5163 Add error handler or log error instead of using "pass" on exception in st2
  contrib/linux/actions/checks/check_processes.py
  contrib/linux/sensors/file_watch_sensor.py
  st2actions/st2actions/cmd/scheduler.py
  st2client/st2client/models/core.py
  st2client/st2client/utils/terminal.py
  st2common/st2common/log.py
  st2common/st2common/runners/base.py
  st2common/st2common/util/jsonify.py
  st2reactor/st2reactor/container/sensor_wrapper.py
Labels: size/M

#5179 Propose adding @winem as a Maintainer
  OWNERS.md
Labels: TSC:voting, size/XS

#5186 Use sudo -E to preserve env vars in CI
  .circle/add-itest-user.sh
  scripts/travis/add-itest-user-key.sh
Labels: infrastructure: ci/cd, size/S

#5187 [v3.4] Backport sudo -E CI fix
  .circle/add-itest-user.sh
  scripts/travis/add-itest-user-key.sh
Labels: infrastructure: ci/cd, size/S

#5162 Refactor spec_loader to use yaml.load with SafeLoader
  CHANGELOG.rst
  st2common/st2common/cmd/validate_api_spec.py
  st2common/st2common/util/spec_loader.py
  st2common/tests/unit/test_spec_loader.py
  st2tests/st2tests/fixtures/specs/__init__.py
  st2tests/st2tests/fixtures/specs/openapi.yaml.j2
Labels: enhancement, security, size/S

#5157 Assert change - replaced assert with if and raised an appropriate exception
  contrib/runners/action_chain_runner/action_chain_runner/action_chain_runner.py
  contrib/runners/python_runner/python_runner/python_action_wrapper.py
  contrib/runners/python_runner/python_runner/python_runner.py
  st2api/st2api/controllers/v1/actionexecutions.py
  st2api/st2api/controllers/v1/keyvalue.py
  st2api/st2api/controllers/v1/triggers.py
  st2client/st2client/models/core.py
  st2common/st2common/bootstrap/actionsregistrar.py
  st2common/st2common/bootstrap/aliasesregistrar.py
  st2common/st2common/bootstrap/configsregistrar.py
  st2common/st2common/bootstrap/policiesregistrar.py
  st2common/st2common/bootstrap/rulesregistrar.py
  st2common/st2common/bootstrap/sensorsregistrar.py
  st2common/st2common/bootstrap/triggersregistrar.py
  st2common/st2common/content/loader.py
  st2common/st2common/content/utils.py
  st2common/st2common/models/api/keyvalue.py
  st2common/st2common/models/system/action.py
  st2common/st2common/rbac/types.py
  st2common/st2common/runners/base.py
  st2common/st2common/services/trace.py
  st2common/st2common/services/triggers.py
  st2common/st2common/transport/announcement.py
  st2common/st2common/transport/reactor.py
  st2common/st2common/util/crypto.py
  st2common/st2common/util/green/shell.py
  st2common/st2common/util/sandboxing.py
  st2common/st2common/util/shell.py
  st2common/st2common/util/templating.py
  st2reactor/st2reactor/container/sensor_wrapper.py
  st2reactor/st2reactor/garbage_collector/base.py
  st2reactor/st2reactor/rules/enforcer.py
Labels: size/L

#5183 Added web security headers for nginx configuration
  CHANGELOG.rst
  conf/nginx/st2.conf
Labels: enhancement, security, size/S

#5176 Add support for limit and offset in list_values method
  CHANGELOG.rst
  st2client/st2client/models/core.py
  st2common/st2common/services/datastore.py
  st2common/tests/unit/test_datastore.py
Labels: enhancement, size/M

#5170 Fix broken badges links in README
  README.md
Labels: size/XS

#5184 Updates for v3.4.1
  CHANGELOG.rst
  st2common/st2common/log.py
  st2common/st2common/service_setup.py
  st2common/tests/integration/log_unicode_data.py
  st2common/tests/integration/test_logging.py
  st2common/tests/integration/test_service_setup_log_level_filtering.py
Labels: bug fix, logging, size/XL

#5007 Import ABC from collections.abc for py 3.10 compatibility
  CHANGELOG.rst
  st2client/st2client/utils/types.py
  st2common/st2common/util/db.py
  st2common/st2common/util/misc.py
  st2common/st2common/util/pack.py
  st2common/st2common/util/types.py
Labels: enhancement, size/S

#5123 Update fixate-requirements.py to cope with PIP 20.3.3
  .github/workflows/ci.yaml
  CHANGELOG.rst
  Makefile
  fixed-requirements.txt
  requirements.txt
  scripts/fixate-requirements.py
  st2actions/requirements.txt
  st2api/requirements.txt
  st2auth/requirements.txt
  st2client/requirements.txt
  st2common/bin/st2-run-pack-tests
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2common/st2common/util/ip_utils.py
  st2exporter/requirements.txt
  st2reactor/requirements.txt
  st2stream/requirements.txt
Labels: enhancement, size/L

#5198 Speed up service start up time by reducing runner registration / extension loading time
  CHANGELOG.rst
  st2common/st2common/bootstrap/runnersregistrar.py
Labels: performance, size/S

#5202 Enable ci-integration tests on GHA (incl fixing a few tests)
  .github/workflows/ci.yaml
  .travis.yml
  Makefile
  contrib/runners/python_runner/python_runner/python_action_wrapper.py
  contrib/runners/python_runner/tests/integration/test_python_action_process_wrapper.py
  contrib/runners/python_runner/tests/integration/test_pythonrunner_behavior.py
  scripts/github/rabbitmq.conf
  scripts/travis/prepare-integration.sh
  st2common/st2common/config.py
  st2common/st2common/util/shell.py
  st2common/st2common/util/virtualenvs.py
  st2common/tests/integration/test_rabbitmq_ssl_listener.py
  test-requirements.txt
  tools/launchdev.sh
Labels: feature, infrastructure: ci/cd, size/L

#5200 Add sensor to list of schemas generated by st2-generate-schemas
  CHANGELOG.rst
  contrib/schemas/README.md
  contrib/schemas/sensor.json
  st2common/bin/st2-generate-schemas
  st2common/bin/st2-validate-pack
  st2common/setup.py
  st2common/st2common/models/api/sensor.py
  st2common/st2common/util/spec_loader.py
  st2common/st2common/util/yml.py
Labels: size/L

#5205 Workaround modified GitHub Actions PATH var
  .github/workflows/ci.yaml
Labels: size/XS

#5203 Various CI code related cleanup
  .github/workflows/ci.yaml
  .travis.yml
  Makefile
  scripts/ci/README.md
  scripts/ci/add-itest-user-key.sh
  scripts/ci/create-and-mount-ramdisk.sh
  scripts/ci/install-requirements.sh
  scripts/ci/permissions-workaround.sh
  scripts/ci/run-nightly-make-task-if-exists.sh
  scripts/ci/submit-codecov-coverage.sh
  scripts/ci/time-command.sh
  scripts/github/README.md
  scripts/github/configure-rabbitmq.sh
  scripts/github/prepare-integration.sh
  scripts/populate-package-meta.sh
  scripts/populate-version.sh
  scripts/travis/build.sh
  scripts/travis/install-and-run-mongodb.sh
  scripts/travis/install-requirements.sh
  scripts/travis/mongod.conf
  scripts/travis/rabbitmq.config
  scripts/write-headers.sh
  st2tests/integration/orquesta/test_wiring_inquiry.py
Labels: infrastructure: ci/cd

#5201 Upgrade paramiko
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2common/requirements.txt
Labels: size/S

#5206 Configure redis coordination backend for orquesta integration tests
  .github/workflows/ci.yaml
  scripts/github/prepare-integration.sh
  st2common/st2common/service_setup.py
  st2common/st2common/services/coordination.py
  st2common/tests/integration/test_service_setup_log_level_filtering.py
  st2common/tests/unit/services/test_synchronization.py
Labels: infrastructure: ci/cd, size/L

#5213 Add changelog entry for RHEL / CentOS 8 "Provides" package metadata bug fix
  CHANGELOG.rst
Labels: size/S

#5197 Implement coditional execution "result" field retrieval for the "/v1/executions/<id>" (get one execution) API endpoint
  CHANGELOG.rst
  st2api/st2api/controllers/resource.py
  st2api/st2api/controllers/v1/actionexecutions.py
  st2api/tests/unit/controllers/v1/test_executions.py
  st2common/st2common/openapi.yaml
  st2common/st2common/openapi.yaml.j2
Labels: API, performance, service: api, size/L

#5215 Update various core and test dependencies to latest stable version
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2actions/requirements.txt
  st2api/requirements.txt
  st2api/st2api/controllers/v1/actionexecutions.py
  st2api/st2api/controllers/v1/aliasexecution.py
  st2api/st2api/controllers/v1/keyvalue.py
  st2api/st2api/controllers/v1/packs.py
  st2api/st2api/controllers/v1/rules.py
  st2api/tests/unit/controllers/v1/test_executions.py
  st2api/tests/unit/controllers/v1/test_executions_auth.py
  st2auth/requirements.txt
  st2client/requirements.txt
  st2common/requirements.txt
  st2common/st2common/exceptions/workflow.py
  st2common/st2common/garbage_collection/inquiries.py
  st2common/st2common/models/utils/profiling.py
  st2common/st2common/persistence/db_init.py
  st2common/st2common/services/inquiry.py
  st2common/tests/unit/services/test_workflow_service_retries.py
  st2common/tests/unit/test_exceptions_workflow.py
  st2exporter/requirements.txt
  st2reactor/requirements.txt
  st2reactor/tests/integration/test_sensor_watcher.py
  st2stream/requirements.txt
  st2tests/requirements.txt
  test-requirements-py27.txt
  test-requirements.txt
Labels: external dependency, size/L
