Repository StackStorm/st2, pull requests merged in 2021-08, with the labels that each got.

#5293 5222 - Skip action update if execution already in completed state.
  contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
  contrib/runners/orquesta_runner/tests/unit/test_policies.py
  contrib/runners/orquesta_runner/tests/unit/test_rerun.py
  contrib/runners/orquesta_runner/tests/unit/test_with_items.py
  st2common/st2common/services/executions.py
  st2common/tests/unit/test_executions_util.py
Labels: size/L

#5315 Fixing Typos
  README.md
Labels: documentation, size/XS

#5316 Remove old and unused instructables directory and ChatOps file
  instructables/chatops.md
Labels: enhancement, complexity:easy, size/XS, maintenance

#5322 Ignore more vim temp files
  .gitignore
Labels: RFR, size/XS, maintenance

#5323 Add license headers and other flake8 fixes for contrib
  contrib/examples/actions/noop.py
  contrib/examples/actions/print_config.py
  contrib/examples/actions/python-mock-core-remote.py
  contrib/examples/actions/python-mock-create-vm.py
  contrib/examples/actions/pythonactions/fibonacci.py
  contrib/examples/actions/pythonactions/forloop_get_github_page.py
  contrib/examples/actions/pythonactions/forloop_increase_index_and_check_condition.py
  contrib/examples/actions/pythonactions/forloop_parse_github_repos.py
  contrib/examples/actions/pythonactions/forloop_push_github_repos.py
  contrib/examples/actions/pythonactions/isprime.py
  contrib/examples/actions/pythonactions/json_string_to_object.py
  contrib/examples/actions/pythonactions/load_and_print_fixture.py
  contrib/examples/actions/pythonactions/object_return.py
  contrib/examples/actions/pythonactions/print_python_environment.py
  contrib/examples/actions/pythonactions/print_python_version.py
  contrib/examples/actions/pythonactions/yaml_string_to_object.py
  contrib/examples/actions/ubuntu_pkg_info/lib/datatransformer.py
  contrib/examples/actions/ubuntu_pkg_info/ubuntu_pkg_info.py
  contrib/examples/lib/environ.py
  contrib/examples/sensors/echo_flask_app.py
  contrib/examples/sensors/fibonacci_sensor.py
  contrib/examples/sensors/sample_polling_sensor.py
  contrib/examples/sensors/sample_sensor.py
  contrib/examples/tests/test_action_isprime.py
  contrib/hello_st2/sensors/sensor1.py
  contrib/packs/tests/test_action_aliases.py
Labels: RFR, size/L, maintenance

#5155 Add a debug contrib pack
  contrib/debug/actions/print_ctx.py
  contrib/debug/actions/print_ctx.yaml
  contrib/debug/actions/python_version.py
  contrib/debug/actions/python_version.yaml
  contrib/debug/actions/pythonpath.py
  contrib/debug/actions/pythonpath.yaml
  contrib/debug/pack.yaml
Labels: enhancement, feature, proposal, size/L

#5324 Delete dead/pointless code
  st2api/tests/__init__.py
  st2auth/tests/fixtures/htpasswd_test
  st2auth/tests/unit/test_auth_backends.py
  st2common/tests/fixtures/mock_runner/__init__.py
  st2common/tests/fixtures/mock_runner/mock_runner.py
  st2common/tests/fixtures/mock_runner/runner.yaml
Labels: RFR, size/M, maintenance

#5325 Fix issue in paramiko test script
  st2common/bin/paramiko_ssh_evenlets_tester.py
Labels: RFR, size/XS, maintenance, bug fix

#5304 Modify API to remove related files on delete of actions/workflows
  CHANGELOG.rst
  st2api/st2api/controllers/v1/actions.py
  st2client/st2client/commands/action.py
  st2common/st2common/exceptions/content.py
  st2common/st2common/services/packs.py
  st2common/tests/unit/services/test_packs.py
Labels: size/L

#5331 Fix running scripts/write-headers.sh on Darwin
  scripts/write-headers.sh
Labels: RFR, tooling, size/XS, maintenance

#5302 update db connect mongo connection test
  CHANGELOG.rst
  st2common/st2common/models/db/__init__.py
Labels: enhancement, size/XS

#5329 [TSC 2021July] Revise GOVERNANCE: Maintainer Activities
  GOVERNANCE.md
Labels: size/XS

#5341 Avoid mongodb compatibility regression by using 'ping' instead of 'hello' command
  CHANGELOG.rst
  st2common/st2common/models/db/__init__.py
Labels: enhancement, size/XS

#5339 Add Jacob (@cognifloyd) to the TSC Maintainers
  OWNERS.md
Labels: size/XS, TSC:voting

#5340 Add AJ (@guzzijones) to the TSC Maintainers
  OWNERS.md
Labels: size/XS, TSC:voting

#5333 Prefer explicit imports from st2client.models
  st2client/st2client/commands/action.py
  st2client/st2client/commands/auth.py
  st2client/st2client/commands/pack.py
  st2client/st2client/commands/policy.py
  st2client/st2client/commands/rule.py
  st2client/st2client/commands/rule_enforcement.py
  st2client/st2client/commands/sensor.py
  st2client/st2client/commands/timer.py
  st2client/st2client/commands/trace.py
  st2client/st2client/commands/trigger.py
  st2client/st2client/commands/triggerinstance.py
  st2client/st2client/commands/webhook.py
  st2common/st2common/services/datastore.py
Labels: refactor, RFR, component:st2client, size/M

#5342 Add Carlos (@nzlosh) to TSC maintainers
  OWNERS.md
Labels: size/XS, TSC:voting

#5343 Proposal: Promote Amanda McGuinness(@amanda11) to Senior Maintainers
  OWNERS.md
Labels: size/XS, TSC:voting
