Repository StackStorm/st2, pull requests merged in 2021-09, with the labels that each got.

#5338 Shutdown kombu consumer on worker shutdown
  CHANGELOG.rst
  st2actions/tests/integration/test_actions_queue_consumer.py
  st2common/st2common/transport/consumers.py
Labels: rabbitmq, size/M, service: action runner, bug fix

#5328 Ensure correct error message when have error decrypting parameter and also have keys that convert
  CHANGELOG.rst
  st2api/st2api/controllers/v1/actionexecutions.py
  st2api/tests/unit/controllers/v1/test_executions.py
  st2common/st2common/services/action.py
  st2common/tests/unit/services/test_action.py
Labels: bug, RFR, size/L

#5351 Bug fix in modified action delete API
  st2api/st2api/controllers/v1/actions.py
  st2api/tests/unit/controllers/v1/test_actions.py
Labels: size/M

#5359 Use Jinja sandboxed environment
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  fixed-requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2common/st2common/util/jinja.py
  st2common/st2common/util/param.py
  tools/st2-analyze-links.py
  tools/visualize_action_chain.py
Labels: size/M

#5360 Action delete API rework - support for action file deletion
  CHANGELOG.rst
  st2api/st2api/controllers/v1/actions.py
  st2api/tests/unit/controllers/v1/test_actions.py
  st2client/st2client/commands/action.py
  st2client/st2client/models/core.py
  st2client/tests/unit/test_models.py
  st2common/st2common/openapi.yaml
  st2common/st2common/openapi.yaml.j2
Labels: size/L

#5368 Add RBAC permission types for key value pairs
  st2common/st2common/rbac/types.py
Labels: size/XS

#5369 Rename prefix of KEY_VALUE permission types to KEY_VALUE_PAIR
  st2common/st2common/openapi.yaml
  st2common/st2common/rbac/types.py
  st2common/tests/unit/test_rbac_types.py
Labels: size/M
