Repository StackStorm/st2, pull requests merged in 2021-07, with the labels that each got.

#5299 Fix version quotes for black
  CHANGELOG.rst
  contrib/runners/action_chain_runner/action_chain_runner/__init__.py
  contrib/runners/announcement_runner/announcement_runner/__init__.py
  contrib/runners/http_runner/http_runner/__init__.py
  contrib/runners/inquirer_runner/inquirer_runner/__init__.py
  contrib/runners/local_runner/local_runner/__init__.py
  contrib/runners/noop_runner/noop_runner/__init__.py
  contrib/runners/orquesta_runner/orquesta_runner/__init__.py
  contrib/runners/python_runner/python_runner/__init__.py
  contrib/runners/remote_runner/remote_runner/__init__.py
  contrib/runners/winrm_runner/winrm_runner/__init__.py
  st2actions/st2actions/__init__.py
  st2api/st2api/__init__.py
  st2auth/st2auth/__init__.py
  st2client/st2client/__init__.py
  st2common/st2common/__init__.py
  st2reactor/st2reactor/__init__.py
  st2stream/st2stream/__init__.py
  st2tests/st2tests/__init__.py
Labels: bug fix, complexity:easy, size/M

#5287 Change minimum garbage_collection TTL to 1 day from 7
  CHANGELOG.rst
  st2common/st2common/constants/garbage_collection.py
Labels: enhancement, size/XS

#5297 Fix README that fails pypi checking
  st2client/README.rst
Labels: bug, size/XS

#5154 Add make targets to reinitialize git submodules
  Makefile
Labels: enhancement, size/S

#5306 Add st2client README checks to CI
  Makefile
  st2client/setup.py
Labels: improvement

#5305 Remove deprecated python3 flag
  CHANGELOG.rst
  st2client/st2client/commands/pack.py
Labels: maintenance

#5109 docs: fix simple typo, workound -> workaround
  st2api/tests/unit/controllers/v1/test_auth.py
  st2api/tests/unit/controllers/v1/test_auth_api_keys.py
Labels: enhancement, maintenance, size/XS
