Repository StackStorm/st2, pull requests merged in 2021-10, with the labels that each got.

#5330 Remove myself from senior maintainers
  OWNERS.md
Labels: size/XS, maintenance

#5311 Update Makefile
  Makefile
Labels: enhancement, python3, size/S, improvement, bug fix

#5286 Add reload systemd to run unit generator for st2ctl
  st2common/bin/st2ctl
Labels: enhancement, feature, size/XS

#5377 use python3 in scripts/populate-package-meta.sh
  scripts/populate-package-meta.sh
Labels: RFR, python3, tooling, size/XS, maintenance, bug fix

#5164 Update keyvalue.py to be able to add new values without leaking them in the shell history.
  CHANGELOG.rst
  st2client/st2client/commands/keyvalue.py
Labels: CLI, component:st2client, size/S

#5379 Update orquesta to v1.5.0
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/S

#5199 Add "--enable-profiler" flag to all the StackStorm services + CLI
  CHANGELOG.rst
  st2client/st2client/shell.py
  st2client/st2client/utils/profiler.py
  st2common/st2common/config.py
  st2common/st2common/service_setup.py
  st2common/st2common/util/profiler.py
Labels: size/L, profiling, debugging, status:needs cla

#5358 Make update_execution() atomic
  CHANGELOG.rst
  st2actions/tests/unit/test_workflow_engine.py
  st2common/st2common/services/executions.py
  st2common/tests/unit/services/test_workflow_service_retries.py
Labels: size/L
