Repository StackStorm/st2, pull requests merged in 2021-02, with the labels that each got.

#5125 Add @bigmstone to StackStorm Friends
  OWNERS.md
Labels: TSC:voting, size/XS

#5138 Fix "st2 action-alias execute" CLI command
  CHANGELOG.rst
  st2api/tests/unit/controllers/v1/test_action_alias.py
  st2client/st2client/commands/action_alias.py
  st2client/st2client/models/core.py
  st2client/tests/base.py
  st2client/tests/unit/test_action_alias.py
  st2tests/st2tests/fixtures/aliases/actions/action1.yaml
Labels: component:st2client, size/L

#5150 Adjust GitHub Actions config to avoid double testing on PRs
  .github/workflows/ci.yaml
  st2common/st2common/models/db/execution.py
Labels: size/S, tests, tooling

#5140 Fix st2client @key=file_path.json notation for specifying complex objects in a file
  CHANGELOG.rst
  st2client/st2client/commands/action.py
  st2client/tests/unit/test_command_actionrun.py
Labels: component:st2client, python3, size/M

#5141 Fix a bug in invalid action alias array parameter casting
  CHANGELOG.rst
  st2api/st2api/controllers/v1/aliasexecution.py
  st2api/tests/unit/controllers/v1/test_action_alias.py
  st2api/tests/unit/controllers/v1/test_alias_execution.py
  st2tests/st2tests/fixtures/aliases/actions/action3.yaml
  st2tests/st2tests/fixtures/aliases/actions/action4.yaml
  st2tests/st2tests/fixtures/aliases/aliases/alias_with_immutable_list_param.yaml
  st2tests/st2tests/fixtures/aliases/aliases/alias_with_immutable_list_param_str_cast.yaml
  st2tests/st2tests/fixturesloader.py
Labels: action aliases, chatops, size/L

#5142 [WIP] Rescue Python path code
  st2common/st2common/models/db/execution.py
  st2common/st2common/util/sandboxing.py
  st2common/tests/unit/test_util_sandboxing.py
Labels: bug, python3, regression, runners, size/L

#5167 Add support to force recreation of packs virtualenvs
  CHANGELOG.rst
  contrib/core/requirements-tests.txt
  st2common/bin/st2ctl
  st2common/st2common/content/bootstrap.py
  st2common/st2common/util/virtualenvs.py
  st2common/tests/integration/test_register_content_script.py
Labels: size/M

#5169 Fix path for pip dir which is used for CI cache to speed up the build
  .github/workflows/ci.yaml
Labels: infrastructure: ci/cd, size/XS
