Repository StackStorm/st2, pull requests merged in 2021-06, with the labels that each got.

#5283 Add focal and remove xenial
  .circleci/config.yml
Labels: OS support, size/XS

#5280 Update nginx config to support TLS v1.3 in addition to TLS v1.2
  CHANGELOG.rst
  conf/HA/nginx/st2.conf.blueprint.sample
  conf/HA/nginx/st2.conf.controller.sample
  conf/nginx/st2.conf
Labels: nginx, security, size/S

#5246 Update sample nginx config with information on how to enable response compression
  conf/nginx/st2.conf
Labels: nginx, size/S

#5253 Support special characters in CLI config parameters
  CHANGELOG.rst
  st2client/st2client/config_parser.py
  st2client/tests/fixtures/test_unicode.ini
  st2client/tests/unit/test_config_parser.py
Labels: CLI, component:st2client, size/S

#5291 Add missing setup.py entry for the new migration script
  st2common/setup.py
Labels: size/XS

#5292 Moving myself (@jjm) to Friends from Contributors
  OWNERS.md
Labels: size/XS

#5288 Add @arms11 as a Contributor
  OWNERS.md
Labels: TSC:voting, size/XS
