Repository StackStorm/st2, pull requests merged in 2021-11, with the labels that each got.

#5427 Update Amanda's email
  OWNERS.md
Labels: size/XS

#5436 Update the StackStorm-Exchange reference
  README.md
Labels: enhancement, documentation, size/XS

#5420 Changelog 3.6
  CHANGELOG.rst
Labels: size/S

#5378 Add changelog entries for 3.6 Release
  CHANGELOG.rst
Labels: size/S

#5445 Replace Forum badge with GH Discussions
  README.md
Labels: documentation, size/XS

#5458 fix wrong quotes (for black) in version string
  contrib/runners/action_chain_runner/action_chain_runner/__init__.py
  contrib/runners/announcement_runner/announcement_runner/__init__.py
  contrib/runners/http_runner/http_runner/__init__.py
  contrib/runners/inquirer_runner/inquirer_runner/__init__.py
  contrib/runners/local_runner/local_runner/__init__.py
  contrib/runners/noop_runner/noop_runner/__init__.py
  contrib/runners/orquesta_runner/orquesta_runner/__init__.py
  contrib/runners/python_runner/python_runner/__init__.py
  contrib/runners/remote_runner/remote_runner/__init__.py
  contrib/runners/winrm_runner/winrm_runner/__init__.py
  st2actions/st2actions/__init__.py
  st2api/st2api/__init__.py
  st2auth/st2auth/__init__.py
  st2client/st2client/__init__.py
  st2common/st2common/__init__.py
  st2reactor/st2reactor/__init__.py
  st2stream/st2stream/__init__.py
  st2tests/st2tests/__init__.py
Labels: size/M, bug fix

#5449 Add Ankur Singh (@rush-skills) as a StackStorm Contributor
  OWNERS.md
Labels: size/XS, TSC:voting
