Repository StackStorm/st2, pull requests merged in 2022-10, with the labels that each got.

#5758 Add GHA workflow to lint with pantsbuild
  .github/workflows/lint.yaml
  CHANGELOG.rst
Labels: size/M, infrastructure: ci/cd, maintenance, pantsbuild

#5751 Use shellcheck (via pantsbuild)
  CHANGELOG.rst
  contrib/core/actions/send_mail/BUILD
  contrib/examples/actions/BUILD
  contrib/examples/actions/bash_ping/BUILD
  contrib/examples/actions/bash_random/BUILD
  contrib/linux/actions/BUILD
  pants.toml
  scripts/BUILD
  st2actions/bin/BUILD
  st2api/bin/BUILD
  st2auth/bin/BUILD
  st2common/bin/BUILD
  st2common/bin/migrations/v2.1/BUILD
  st2common/bin/migrations/v3.5/BUILD
  st2common/tests/fixtures/BUILD
  st2reactor/bin/BUILD
  st2stream/bin/BUILD
  st2tests/integration/BUILD
  st2tests/st2tests/fixtures/packs/BUILD
  st2tests/testpacks/errorcheck/actions/BUILD
  tools/BUILD
Labels: size/M, infrastructure: ci/cd, maintenance, pantsbuild

#5774 Use black (via pantsbuild)
  .github/workflows/lint.yaml
  CHANGELOG.rst
  lockfiles/black.lock
  pants.toml
  st2tests/st2tests/fixtures/packs/BUILD
Labels: enhancement, external dependency, size/L, infrastructure: ci/cd, maintenance, pantsbuild

#5776 Use flake8 (via pantsbuild)
  .github/workflows/lint.yaml
  CHANGELOG.rst
  lockfiles/flake8.lock
  pants.toml
  st2actions/bin/BUILD
  st2api/bin/BUILD
  st2auth/bin/BUILD
  st2common/bin/BUILD
  st2reactor/bin/BUILD
  st2stream/bin/BUILD
Labels: external dependency, size/L, infrastructure: ci/cd, pantsbuild

#5777 Use bandit (via pantsbuild)
  .github/workflows/lint.yaml
  CHANGELOG.rst
  lockfiles/bandit.lock
  pants.toml
  st2tests/st2tests/fixtures/packs/BUILD
Labels: external dependency, size/XL, infrastructure: ci/cd, pantsbuild

#5782 Update GHA pants-init action to fix build
  .github/workflows/lint.yaml
  .github/workflows/pants.yaml
  CHANGELOG.rst
  pants
Labels: size/M, infrastructure: ci/cd, maintenance, pantsbuild

#5764 Apply RBAC to rendering of KVP during action execution
  CHANGELOG.rst
  st2common/st2common/services/keyvalues.py
  st2common/st2common/util/keyvalue.py
  st2common/st2common/util/param.py
  st2common/tests/unit/test_keyvalue_lookup.py
  st2common/tests/unit/test_util_keyvalue.py
Labels: RBAC, size/L

#5783 Add backward compatibility to secret masking for output schema
  CHANGELOG.rst
  st2common/st2common/util/output_schema.py
  st2common/tests/unit/test_util_output_schema.py
Labels: size/M
