Repository StackStorm/st2, pull requests merged in 2022-02, with the labels that each got.

#5555 Link shutdown routine and sigterm handler to main thread
  .github/workflows/ci.yaml
  .github/workflows/orquesta-integration-tests.yaml
  st2actions/st2actions/cmd/actionrunner.py
  st2actions/st2actions/cmd/workflow_engine.py
  st2common/st2common/transport/consumers.py
Labels: size/M

#5556 check if value is actually jinja before adding as template
  CHANGELOG.rst
  st2common/st2common/util/param.py
  st2common/tests/unit/test_param_utils.py
Labels: size/M

#5564 Add a Changelog Checker
  .github/workflows/checks.yaml
Labels: enhancement, size/S, no changelog

#5568 Change compound index to improve query performance
  CHANGELOG.rst
  st2common/st2common/models/db/execution.py
Labels: size/S

#5538 WinRM parameter passing fails for larger scripts
  CHANGELOG.rst
  contrib/runners/winrm_runner/tests/unit/test_winrm_base.py
  contrib/runners/winrm_runner/winrm_runner/winrm_base.py
Labels: size/S, bug fix

#5581 Fix build failures due to newer MarkUpSafe
  .github/workflows/ci.yaml
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2actions/in-requirements.txt
  st2actions/requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/M, bug fix
