Repository StackStorm/st2, pull requests merged in 2022-12, with the labels that each got.

#5795 Inform Pants about our target python versions (3.6 and 3.8)
  CHANGELOG.rst
  lockfiles/bandit.lock
  lockfiles/black.lock
  lockfiles/flake8.lock
  pants.toml
Labels: external dependency, python3, size/XL, pantsbuild

#5830 pantsbuild: Generate PEX lockfile for st2
  CHANGELOG.rst
  lockfiles/st2.lock
  pants.toml
Labels: external dependency, python3, size/XXL, pantsbuild

#5832 pin GHA runners to ubuntu-20.04
  .github/workflows/checks.yaml
  .github/workflows/ci.yaml
  .github/workflows/lint.yaml
  .github/workflows/microbenchmarks.yaml
  .github/workflows/orquesta-integration-tests.yaml
  .github/workflows/pants.yaml
Labels: size/S, no changelog

#5833 pants: disambiguate test file dependencies
  CHANGELOG.rst
  contrib/core/tests/BUILD
  contrib/packs/tests/BUILD
  contrib/runners/orquesta_runner/tests/unit/BUILD
  st2auth/tests/unit/BUILD
  st2auth/tests/unit/controllers/v1/BUILD
  st2client/tests/unit/BUILD
  st2common/tests/unit/BUILD
Labels: size/M, pantsbuild

#5834 pants: register requirements for contrib/examples pack
  CHANGELOG.rst
  contrib/examples/BUILD
  lockfiles/st2.lock
Labels: external dependency, size/L, pantsbuild

#5836 Add DigitalOcean as an adopter
  ADOPTERS.md
Labels: size/XS, no changelog

#5840 Generate lockfile for using setuptools
  CHANGELOG.rst
  lockfiles/setuptools.lock
  pants.toml
Labels: st2-packages, external dependency, size/L, pantsbuild

#5838 Generate lockfile for using pytest
  CHANGELOG.rst
  lockfiles/pytest.lock
  pants.toml
Labels: external dependency, size/XL, pantsbuild

#5842 Configure pants to look for plugins in pants-plugins/ directory
  CHANGELOG.rst
  lockfiles/pants-plugins.lock
  pants-plugins/BUILD
  pants-plugins/README.md
  pants.toml
Labels: external dependency, size/XXL, pantsbuild

#5849 use a fixture for pylint_plugins test
  CHANGELOG.rst
  pylint_plugins/BUILD
  pylint_plugins/api_models_test.py
  pylint_plugins/fixtures/BUILD
  pylint_plugins/fixtures/__init__.py
  pylint_plugins/fixtures/api_models.py
  st2common/st2common/models/api/action.py
  st2common/st2common/models/api/base.py
  st2common/st2common/models/api/notification.py
  st2common/st2common/models/api/trigger.py
Labels: tests, size/L, pantsbuild

#5850 Update metadata+lockfiles to support testing pants-plugins/
  CHANGELOG.rst
  Makefile
  lockfiles/bandit.lock
  lockfiles/flake8.lock
  lockfiles/pants-plugins.lock
  lockfiles/pytest.lock
  lockfiles/twine.lock
  pants-plugins/BUILD
Labels: tests, external dependency, size/L, infrastructure: ci/cd, pantsbuild

#5852 Add Mark Mercado (@mamercad) to the StackStorm Contributors
  OWNERS.md
Labels: size/XS, TSC:voting, no changelog
