Repository StackStorm/st2, pull requests merged in 2022-01, with the labels that each got.

#5468 Enable setting ttl for MockDatastoreService
  CHANGELOG.rst
  st2tests/st2tests/mocks/datastore.py
Labels: enhancement, size/S

#5469 #5460 - Include pysocks in st2client
  CHANGELOG.rst
  requirements.txt
  st2client/in-requirements.txt
  st2client/requirements.txt
Labels: enhancement, size/XS

#5462 fix: timediff typo
  CHANGELOG.rst
  st2common/st2common/operators.py
  st2common/tests/unit/test_operators.py
Labels: size/M, bug fix

#5529 Use byte type lock name which is supported by all tooz drivers
  CHANGELOG.rst
  st2common/st2common/services/executions.py
  st2common/st2common/services/workflows.py
Labels: size/XS, bug fix

#5535 Add changelog for ldap backend
  CHANGELOG.rst
Labels: enhancement, size/XS

#5509 Adding get_by_ref for ParametersViewController
  CHANGELOG.rst
  st2api/st2api/controllers/v1/action_views.py
  st2api/tests/unit/controllers/v1/test_action_views.py
  st2common/st2common/openapi.yaml
  st2common/st2common/openapi.yaml.j2
Labels: enhancement, API, size/M

#5428 Graceful shutdown of action runner.
  CHANGELOG.rst
  conf/st2.conf.sample
  st2actions/st2actions/worker.py
  st2actions/tests/unit/test_worker.py
  st2common/st2common/config.py
Labels: feature, size/L, service: action runner

#5482 Added 'multiple' operator to allow complex criteria matching on payload items
  CHANGELOG.rst
  st2common/st2common/operators.py
  st2common/tests/unit/test_operators.py
  st2reactor/st2reactor/rules/filter.py
  st2reactor/tests/unit/test_filter.py
Labels: feature, size/L

#5554 Add status changed by user info to context
  CHANGELOG.rst
  contrib/runners/orquesta_runner/tests/unit/test_cancel.py
  contrib/runners/orquesta_runner/tests/unit/test_pause_and_resume.py
  st2common/st2common/services/action.py
Labels: enhancement, size/M

#5038 Fix for issue 4998 - Web Hook Rules check http headers in case sensitive manner
  CHANGELOG.rst
  st2api/st2api/controllers/v1/webhooks.py
  st2api/tests/unit/controllers/v1/test_webhooks.py
Labels: enhancement, API, size/M, bug fix

#5534 Fix issue with pack option not working when running policy list cli
  CHANGELOG.rst
  st2client/st2client/commands/policy.py
  st2client/tests/unit/test_shell.py
Labels: CLI, policies, size/M, bug fix

#5557 Pin pyOpenSSL to <= 21.0.0
  fixed-requirements.txt
  requirements.txt
  st2client/in-requirements.txt
  st2client/requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: size/XS, bug fix
