Repository StackStorm/st2, pull requests merged in 2022-07, with the labels that each got.

#5321 Pack config: Process defaults and datastore values in patternProperties and additionalItems
  CHANGELOG.rst
  st2common/st2common/util/config_loader.py
  st2common/tests/unit/test_config_loader.py
  st2tests/st2tests/fixtures/packs/dummy_pack_schema_with_additional_items_1/config.schema.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_schema_with_additional_items_1/pack.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_schema_with_pattern_and_additional_properties_1/config.schema.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_schema_with_pattern_and_additional_properties_1/pack.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_schema_with_pattern_properties_1/config.schema.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_schema_with_pattern_properties_1/pack.yaml
Labels: enhancement, size/XL, bug fix

#5347 make http/https_proxy env var checking case insensitive (address issue #5137)
  CHANGELOG.rst
  st2client/st2client/base.py
Labels: component:st2client, size/S, bug fix

#5669 drop unused imports in contrib/debug/actions
  contrib/debug/actions/print_ctx.py
  contrib/debug/actions/python_version.py
Labels: refactor, size/XS, no changelog

#5672 Add misc pylint ignores for false positives
  contrib/runners/winrm_runner/winrm_runner/winrm_base.py
  contrib/runners/winrm_runner/winrm_runner/winrm_command_runner.py
  contrib/runners/winrm_runner/winrm_runner/winrm_ps_command_runner.py
  lint-configs/python/.pylintrc
  st2common/benchmarks/micro/test_mongo_field_types.py
  st2common/bin/migrations/v3.1/st2-cleanup-policy-delayed.py
Labels: size/S, maintenance, no changelog

#5319 Allow `output_schema` to validate non-object action output (int, bool, etc)
  CHANGELOG.rst
  contrib/runners/action_chain_runner/action_chain_runner/runner.yaml
  contrib/runners/http_runner/http_runner/runner.yaml
  contrib/runners/orquesta_runner/orquesta_runner/runner.yaml
  contrib/runners/python_runner/python_runner/runner.yaml
  contrib/runners/python_runner/tests/unit/test_output_schema.py
  contrib/schemas/action.json
  st2api/tests/unit/controllers/v1/test_executions.py
  st2common/st2common/models/api/action.py
  st2common/st2common/util/output_schema.py
  st2common/st2common/util/schema/__init__.py
  st2common/tests/unit/services/test_packs.py
  st2common/tests/unit/test_db_execution.py
  st2common/tests/unit/test_util_output_schema.py
  st2tests/st2tests/fixtures/generic/runners/run-local.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_1/actions/my_http_action.yaml
  st2tests/st2tests/fixtures/packs/dummy_pack_1/actions/my_py_action.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/data-flow.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/py-secret-output.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/sequential_with_broken_schema.yaml
  st2tests/st2tests/fixtures/packs/orquesta_tests/actions/sequential_with_schema.yaml
Labels: enhancement, size/XXL, bug fix, output schema

#5670 use the runner.yaml constant
  st2common/st2common/runners/base.py
Labels: refactor, size/XS, no changelog

#5671 delete pointless py header in empty __init__.py
  st2tests/st2tests/fixtures/packs/dummy_pack_23/actions/workflows/__init__.py
Labels: refactor, size/S, no changelog

#5675 add ST2_USE_DEBUGGER env var to mirror --use-debugger arg
  CHANGELOG.rst
  st2common/st2common/util/monkey_patch.py
Labels: enhancement, size/XS

#5298 Changed X-XSS-Protection to follow OWASP standards due to deprecation.
  CHANGELOG.rst
  conf/nginx/st2.conf
Labels: security, size/XS, nginx

#5678 fix use correct os environ to check HTTPS_PROXY
  CHANGELOG.rst
  st2client/st2client/base.py
Labels: size/XS, status:needs cla

#5679 Add purging of old tokens
  CHANGELOG.rst
  conf/st2.conf.sample
  st2common/bin/st2-purge-tokens
  st2common/setup.py
  st2common/st2common/cmd/purge_tokens.py
  st2common/st2common/garbage_collection/token.py
  st2common/st2common/persistence/auth.py
  st2common/tests/unit/test_purge_token.py
  st2reactor/st2reactor/garbage_collector/base.py
  st2reactor/st2reactor/garbage_collector/config.py
  st2tests/st2tests/config.py
Labels: enhancement, size/L

#5676 Drop st2exporter
  CHANGELOG.rst
  conf/HA/st2.conf.sample
  conf/st2.conf.sample
  conf/st2.dev.conf
  conf/st2.package.conf
  conf/st2.tests.conf
  conf/st2.tests1.conf
  conf/st2.tests2.conf
  st2common/bin/migrations/v3.8/st2-drop-st2exporter-marker-collections
  st2common/st2common/models/db/marker.py
  st2common/st2common/persistence/marker.py
  st2common/st2common/transport/queues.py
  st2common/tests/unit/test_db_marker.py
  st2exporter/MANIFEST.in
  st2exporter/Makefile
  st2exporter/README.md
  st2exporter/bin/st2exporter
  st2exporter/conf/logging.exporter.conf
  st2exporter/conf/st2exporter.dev.conf
  st2exporter/conf/syslog.exporter.conf
  st2exporter/dist_utils.py
  st2exporter/in-requirements.txt
  st2exporter/requirements.txt
  st2exporter/setup.py
  st2exporter/st2exporter/__init__.py
  st2exporter/st2exporter/cmd/__init__.py
  st2exporter/st2exporter/cmd/st2exporter_starter.py
  st2exporter/st2exporter/config.py
  st2exporter/st2exporter/exporter/__init__.py
  st2exporter/st2exporter/exporter/dumper.py
  st2exporter/st2exporter/exporter/file_writer.py
  st2exporter/st2exporter/exporter/json_converter.py
  st2exporter/st2exporter/worker.py
  st2exporter/tests/integration/__init__.py
  st2exporter/tests/integration/test_dumper_integration.py
  st2exporter/tests/integration/test_export_worker.py
  st2exporter/tests/unit/__init__.py
  st2exporter/tests/unit/test_dumper.py
  st2exporter/tests/unit/test_json_converter.py
  st2tests/st2tests/config.py
  st2tests/st2tests/fixtures/conf/st2.tests.api.audit_log_level.conf
  st2tests/st2tests/fixtures/conf/st2.tests.api.debug_log_level.conf
  st2tests/st2tests/fixtures/conf/st2.tests.api.info_log_level.conf
  st2tests/st2tests/fixtures/conf/st2.tests.api.system_debug_true.conf
  st2tests/st2tests/fixtures/conf/st2.tests.api.system_debug_true_logging_debug.conf
  st2tests/st2tests/fixtures/conf/st2.tests.conf
  tools/config_gen.py
  tools/launchdev.sh
Labels: refactor, st2-packages, metrics, size/XXL

#5673 Use PEP 440 style requirements
  CHANGELOG.rst
  contrib/linux/requirements.txt
  contrib/runners/action_chain_runner/dist_utils.py
  contrib/runners/announcement_runner/dist_utils.py
  contrib/runners/http_runner/dist_utils.py
  contrib/runners/inquirer_runner/dist_utils.py
  contrib/runners/local_runner/dist_utils.py
  contrib/runners/noop_runner/dist_utils.py
  contrib/runners/orquesta_runner/dist_utils.py
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  contrib/runners/python_runner/dist_utils.py
  contrib/runners/remote_runner/dist_utils.py
  contrib/runners/winrm_runner/dist_utils.py
  fixed-requirements.txt
  requirements.txt
  scripts/dist_utils.py
  scripts/fixate-requirements.py
  st2actions/dist_utils.py
  st2actions/in-requirements.txt
  st2actions/requirements.txt
  st2api/dist_utils.py
  st2auth/dist_utils.py
  st2auth/in-requirements.txt
  st2auth/requirements.txt
  st2client/dist_utils.py
  st2common/dist_utils.py
  st2common/in-requirements.txt
  st2common/requirements.txt
  st2reactor/dist_utils.py
  st2stream/dist_utils.py
  st2tests/dist_utils.py
Labels: refactor, external dependency, size/L

#5685 Fix schema utils handling of nested arrays
  CHANGELOG.rst
  st2common/st2common/util/schema/__init__.py
  st2common/tests/unit/test_json_schema.py
Labels: refactor, API, RBAC, size/L, bug fix, output schema

#5686 Add pytest config section to pyproject.toml
  pyproject.toml
Labels: tests, size/XS, maintenance, no changelog
