Repository StackStorm/st2, pull requests merged in 2023-03, with the labels that each got.

#5899 Upgrade pants from 2.14 to 2.15
  CHANGELOG.rst
  lockfiles/pants-plugins.lock
  pants-plugins/api_spec/rules.py
  pants-plugins/api_spec/rules_test.py
  pants-plugins/api_spec/subsystem.py
  pants-plugins/sample_conf/rules.py
  pants-plugins/sample_conf/rules_test.py
  pants-plugins/sample_conf/subsystem.py
  pants-plugins/schemas/rules.py
  pants-plugins/schemas/rules_test.py
  pants-plugins/schemas/subsystem.py
  pants.toml
Labels: enhancement, external dependency, size/XXL, pantsbuild

#5907 Pants: add `python_distribution` BUILD metadata for runners
  CHANGELOG.rst
  contrib/runners/action_chain_runner/BUILD
  contrib/runners/announcement_runner/BUILD
  contrib/runners/http_runner/BUILD
  contrib/runners/inquirer_runner/BUILD
  contrib/runners/local_runner/BUILD
  contrib/runners/noop_runner/BUILD
  contrib/runners/orquesta_runner/BUILD
  contrib/runners/python_runner/BUILD
  contrib/runners/remote_runner/BUILD
  contrib/runners/winrm_runner/BUILD
  pants-plugins/macros.py
Labels: runners, size/L, pantsbuild

#5909 Pants: add `python_distribution` BUILD metadata for st2* components
  CHANGELOG.rst
  pants-plugins/macros.py
  st2actions/BUILD
  st2api/BUILD
  st2auth/BUILD
  st2client/BUILD
  st2common/BUILD
  st2common/bin/st2-purge-task-executions
  st2common/bin/st2-purge-workflows
  st2reactor/BUILD
  st2stream/BUILD
  st2tests/BUILD
Labels: size/M, pantsbuild

#5922 Misc cleanups
  CHANGELOG.rst
  contrib/packs/actions/pack_mgmt/unload.py
  contrib/packs/tests/BUILD
  lockfiles/st2-constraints.txt
  requirements-pants.txt
  st2common/st2common/cmd/purge_executions.py
  st2common/st2common/cmd/purge_rule_enforcements.py
  st2common/st2common/cmd/purge_tokens.py
  st2common/st2common/cmd/purge_traces.py
  st2common/st2common/cmd/purge_trigger_instances.py
  st2reactor/st2reactor/rules/tester.py
Labels: refactor, size/S, pantsbuild

#5926 Pants: reclassify test utils in BUILD metadata
  CHANGELOG.rst
  contrib/runners/orquesta_runner/tests/unit/BUILD
  st2client/tests/BUILD
  st2common/tests/unit/BUILD
  st2tests/integration/orquesta/BUILD
Labels: size/S, pantsbuild

#5927 Pants: add some missing external dependencies
  CHANGELOG.rst
  lockfiles/st2.lock
  st2actions/conf/BUILD
  st2client/BUILD
  st2common/st2common/util/BUILD
  st2common/st2common/util/concurrency.py
  st2common/st2common/util/monkey_patch.py
  tools/BUILD
  tools/st2-analyze-links.py
  tools/visualize_action_chain.py
Labels: external dependency, size/L, pantsbuild

#5925 Pants: add dependencies to the st2common `python_distribution`
  CHANGELOG.rst
  st2common/BUILD
  st2common/bin/BUILD
  st2common/bin/migrations/v3.5/BUILD
  st2common/bin/migrations/v3.8/BUILD
  st2common/bin/migrations/v3.8/st2-drop-st2exporter-marker-collections
Labels: size/M, pantsbuild

#5928 Pants: add dependencies to the st2* `python_distributions` (except st2common/st2tests)
  CHANGELOG.rst
  pants.toml
  st2actions/BUILD
  st2api/st2api/BUILD
  st2api/st2api/controllers/BUILD
  st2auth/st2auth/BUILD
  st2auth/st2auth/backends/BUILD
  st2reactor/st2reactor/container/BUILD
  st2stream/st2stream/BUILD
Labels: size/M, pantsbuild

#5929 Pants: add dependencies to the st2tests `python_distributions`
  CHANGELOG.rst
  st2actions/tests/unit/test_actions_registrar.py
  st2common/tests/unit/BUILD
  st2tests/BUILD
  st2tests/st2tests/BUILD
  st2tests/st2tests/fixtures/generic/fixture.py
  st2tests/st2tests/fixtures/localrunner_pack/BUILD
  st2tests/st2tests/fixtures/packs/dummy_pack_1/BUILD
  st2tests/st2tests/fixtures/packs/dummy_pack_1/etc/BUILD
  st2tests/st2tests/fixtures/packs/dummy_pack_2/BUILD
  st2tests/st2tests/fixtures/packs/dummy_pack_3/BUILD
  st2tests/st2tests/fixtures/packs/dummy_pack_7/BUILD
  st2tests/st2tests/fixtures/packs/dummy_pack_9/BUILD
  st2tests/st2tests/fixtures/packs/dummy_pack_9/actions/invalid_syntax.py
  st2tests/st2tests/fixtures/packs/orquesta_tests/BUILD
  st2tests/st2tests/fixtures/packs/pack_invalid_requirements/BUILD
  st2tests/st2tests/fixtures/packs/runners/BUILD
  st2tests/st2tests/fixtures/packs/runners/test_async_runner/BUILD
  st2tests/st2tests/fixtures/packs/runners/test_polling_async_runner/BUILD
  st2tests/st2tests/fixtures/packs/test_library_dependencies/BUILD
  st2tests/st2tests/fixtures/specs/BUILD
  st2tests/st2tests/fixtures/ssl_certs/BUILD
  st2tests/st2tests/policies/meta/BUILD
Labels: tests, size/L, pantsbuild

#5930 Add pants source roots and a constant for pack common lib directory
  CHANGELOG.rst
  contrib/runners/python_runner/tests/unit/test_pythonrunner.py
  pants.toml
  st2common/st2common/constants/pack.py
  st2common/st2common/util/pack.py
  st2common/st2common/util/sandboxing.py
Labels: refactor, size/S, packs, pantsbuild

#5931 Pants: reclassify test utils in BUILD metadata (part 2)
  CHANGELOG.rst
  st2actions/BUILD
  st2auth/tests/BUILD
  st2common/tests/integration/BUILD
  st2stream/tests/unit/controllers/v1/BUILD
Labels: tests, size/S, pantsbuild

#5775 Add option to dig so we can specify type
  CHANGELOG.rst
  contrib/linux/actions/dig.py
  contrib/linux/actions/dig.yaml
  contrib/linux/pack.yaml
  contrib/linux/tests/test_action_dig.py
Labels: enhancement, size/M

#5932 Upgrade pants from 2.15 to 2.16.0a0
  BUILD
  CHANGELOG.rst
  contrib/core/BUILD
  contrib/packs/tests/BUILD
  contrib/runners/orquesta_runner/tests/unit/BUILD
  lockfiles/pants-plugins.lock
  lockfiles/st2.lock
  pants-plugins/macros.py
  pants.toml
  st2auth/st2auth/backends/__init__.py
  st2auth/st2auth/sso/__init__.py
  st2auth/tests/unit/BUILD
  st2auth/tests/unit/controllers/v1/BUILD
  st2client/tests/unit/BUILD
  st2common/st2common/constants/runners.py
  st2common/st2common/metrics/base.py
  st2common/st2common/rbac/backends/__init__.py
  st2common/st2common/runners/__init__.py
  st2common/st2common/util/driver_loader.py
  st2common/tests/integration/BUILD
  st2common/tests/unit/BUILD
  st2common/tests/unit/migrations/BUILD
  st2common/tests/unit/services/BUILD
  st2common/tests/unit/test_action_db_utils.py
  tools/BUILD
  tools/config_gen.py
Labels: size/XL, pantsbuild

#5948 chore: standardize format of BUILD overrides
  BUILD
  CHANGELOG.rst
  contrib/core/tests/BUILD
  contrib/examples/actions/bash_random/BUILD
  pants-plugins/uses_services/BUILD
  st2actions/conf/BUILD
  st2common/bin/BUILD
  st2common/st2common/bootstrap/BUILD
  tools/BUILD
Labels: refactor, size/M, pantsbuild
