Repository StackStorm/st2, pull requests merged in 2023-02, with the labels that each got.

#5864 Add `pants-plugins/uses_services` to check before running tests for required services (like mongo)
  .github/workflows/test.yaml
  CHANGELOG.rst
  pants-plugins/README.md
  pants-plugins/uses_services/BUILD
  pants-plugins/uses_services/__init__.py
  pants-plugins/uses_services/data_fixtures.py
  pants-plugins/uses_services/exceptions.py
  pants-plugins/uses_services/mongo_rules.py
  pants-plugins/uses_services/mongo_rules_test.py
  pants-plugins/uses_services/platform_rules.py
  pants-plugins/uses_services/platform_rules_test.py
  pants-plugins/uses_services/register.py
  pants-plugins/uses_services/scripts/BUILD
  pants-plugins/uses_services/scripts/__init__.py
  pants-plugins/uses_services/scripts/inspect_platform.py
  pants-plugins/uses_services/scripts/is_mongo_running.py
  pants-plugins/uses_services/target_types.py
  pants.toml
  st2common/tests/unit/BUILD
  st2common/tests/unit/services/BUILD
Labels: tests, database, size/XL, infrastructure: ci/cd, pantsbuild

#5845 clone packs into user_home/.st2packs directory
  CHANGELOG.rst
  st2common/st2common/util/pack_management.py
Labels: size/XS

#5763 Add publisher to ActionAlias
  CHANGELOG.rst
  st2common/st2common/persistence/actionalias.py
  st2common/st2common/stream/listener.py
  st2common/st2common/transport/actionalias.py
  st2common/st2common/transport/bootstrap_utils.py
  st2common/st2common/transport/queues.py
Labels: feature, chatops, size/M, action aliases, hacktoberfest-accepted

#5893 Update `pants-plugins/uses_services` to support checking for redis
  .github/workflows/test.yaml
  CHANGELOG.rst
  contrib/runners/orquesta_runner/tests/integration/BUILD
  pants-plugins/uses_services/BUILD
  pants-plugins/uses_services/redis_rules.py
  pants-plugins/uses_services/redis_rules_test.py
  pants-plugins/uses_services/scripts/is_redis_running.py
  st2tests/integration/orquesta/BUILD
Labels: tests, size/L, infrastructure: ci/cd, pantsbuild

#5891 Add `pants-plugins/release` to handle wheel metadata generation
  CHANGELOG.rst
  pants-plugins/README.md
  pants-plugins/release/BUILD
  pants-plugins/release/__init__.py
  pants-plugins/release/register.py
  pants-plugins/release/rules.py
  pants-plugins/release/rules_test.py
  pants.toml
  st2client/setup.py
Labels: enhancement, size/XL, maintenance, pantsbuild

#5890 pants: Add `st2_shell_sources_and_resources()` macro to `pants-plugins/macros.py`
  CHANGELOG.rst
  pants-plugins/BUILD
  pants-plugins/README.md
  pants-plugins/macros.py
  pants.toml
  st2actions/bin/BUILD
  st2common/bin/BUILD
  st2tests/st2tests/fixtures/generic/BUILD
  st2tests/st2tests/fixtures/generic/actions/BUILD
  st2tests/st2tests/fixtures/packs/BUILD
Labels: size/M, maintenance, pantsbuild

#5898 Pants: Misc `pants-plugins/uses_services` improvements
  CHANGELOG.rst
  pants-plugins/uses_services/mongo_rules_test.py
  pants-plugins/uses_services/register.py
Labels: enhancement, size/XS, pantsbuild

#5901 pants: Add `st2_*_python_distribution()` macros to `pants-plugins/macros.py`
  BUILD
  CHANGELOG.rst
  pants-plugins/macros.py
Labels: size/L, pantsbuild

#5911 expose action parameter debug to all actions
  CHANGELOG.rst
  st2common/st2common/runners/base.py
Labels: size/XS, service: action runner
