Repository StackStorm/st2, pull requests merged in 2023-01, with the labels that each got.

#5855 Move JP from TSC to Friends
  OWNERS.md
Labels: size/XS, TSC, no changelog

#5847 Add `pants-plugins/schemas` to streamline regenerating `contrib/schemas`
  CHANGELOG.rst
  contrib/schemas/BUILD
  pants-plugins/README.md
  pants-plugins/schemas/BUILD
  pants-plugins/schemas/__init__.py
  pants-plugins/schemas/register.py
  pants-plugins/schemas/rules.py
  pants-plugins/schemas/rules_test.py
  pants-plugins/schemas/target_types.py
  pants.toml
Labels: size/L, infrastructure: ci/cd, pantsbuild

#5857 Add `pants-plugins/api_spec` to streamline regenerating `openapi.yaml`
  CHANGELOG.rst
  Makefile
  pants-plugins/README.md
  pants-plugins/api_spec/BUILD
  pants-plugins/api_spec/__init__.py
  pants-plugins/api_spec/register.py
  pants-plugins/api_spec/rules.py
  pants-plugins/api_spec/rules_test.py
  pants-plugins/api_spec/target_types.py
  pants.toml
  st2common/st2common/BUILD
  st2common/st2common/cmd/generate_api_spec.py
Labels: size/XL, pantsbuild

#5860 Add `pants-plugins/sample_conf` to streamline regenerating `conf/st2.conf.sample`
  BUILD
  CHANGELOG.rst
  conf/BUILD
  pants-plugins/README.md
  pants-plugins/sample_conf/BUILD
  pants-plugins/sample_conf/__init__.py
  pants-plugins/sample_conf/register.py
  pants-plugins/sample_conf/rules.py
  pants-plugins/sample_conf/rules_test.py
  pants-plugins/sample_conf/target_types.py
  pants.toml
  tools/BUILD
  tools/config_gen.py
Labels: size/L, pantsbuild

#5868 Add `pants-plugins/pack_metadata` to inform pants about our packs
  CHANGELOG.rst
  pants-plugins/README.md
  pants-plugins/pack_metadata/BUILD
  pants-plugins/pack_metadata/__init__.py
  pants-plugins/pack_metadata/register.py
  pants-plugins/pack_metadata/tailor.py
  pants-plugins/pack_metadata/tailor_test.py
  pants-plugins/pack_metadata/target_types.py
  pants-plugins/pack_metadata/target_types_test.py
  pants.toml
  st2tests/st2tests/fixtures/packs/BUILD
Labels: enhancement, tests, size/L, infrastructure: ci/cd, pantsbuild
