Repository StackStorm/st2, pull requests merged in 2023-11, with the labels that each got.

#6055 Update cryptography and pyOpenSSL (security)
  CHANGELOG.rst
  contrib/runners/python_runner/python_runner/python_action_wrapper.py
  fixed-requirements.txt
  requirements.txt
  st2client/requirements.txt
  st2client/st2client/shell.py
  st2common/requirements.txt
  st2common/tests/integration/log_unicode_data.py
  st2common/tests/integration/test_logging.py
Labels: enhancement, security, external dependency, size/M

#6061 Bump eventlet to fix setting SSLContext minimum_version property that results in RecursionErrors
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2actions/requirements.txt
  st2api/requirements.txt
  st2auth/requirements.txt
  st2common/requirements.txt
  st2reactor/requirements.txt
  st2stream/requirements.txt
  test-requirements.txt
Labels: enhancement, security, size/M

#6049 Fix st2 cli client auth in st2auth proxy mode
  CHANGELOG.rst
  st2auth/st2auth/handlers.py
  st2auth/tests/unit/test_handlers.py
Labels: enhancement, size/M

#6060 Enhancements to Adopters.md
  ADOPTERS.md
Labels: documentation, size/XS, no changelog

#6050 Update Orquesta to v1.6.0
  CHANGELOG.rst
  contrib/runners/orquesta_runner/in-requirements.txt
  contrib/runners/orquesta_runner/requirements.txt
  fixed-requirements.txt
  requirements-pants.txt
  requirements.txt
  st2common/in-requirements.txt
  st2common/requirements.txt
Labels: security, size/S

#6068 Bump ruby 2.6 -> 2.7 to fix packagecloud deploy step
  .circleci/config.yml
Labels: bug, external dependency, size/XS, no changelog

#5936 bugfix/ISSUE-5934-fix-rbac-kv-value-render
  CHANGELOG.rst
  st2common/st2common/services/keyvalues.py
Labels: size/S

#6063 Update gitpython (security)
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2actions/requirements.txt
  st2common/requirements.txt
Labels: enhancement, security, size/S

#6067 Add Schwarz Digits to ADOPTERS.md
  ADOPTERS.md
Labels: size/XS, no changelog

#6070 ‎contrib/examples/sensors/echo_flask_app.py Snyk Finding Cross-site Scripting (XSS)
  CHANGELOG.rst
  contrib/examples/sensors/echo_flask_app.py
Labels: enhancement, size/XS

#6072 Update importlib-metadata (security)
  CHANGELOG.rst
  fixed-requirements.txt
  requirements.txt
  st2client/requirements.txt
Labels: security, size/S

#6073 For "local-shell-script" runner, on readonly filesystems, don't attempt to run chmod +x on script_action.
  CHANGELOG.rst
  contrib/runners/local_runner/local_runner/base.py
Labels: bug, HA, size/XS
