Repository StackStorm/st2, pull requests merged in 2023-10, with the labels that each got.

#6028 fix(st2common/router): don't log sensitive information
  CHANGELOG.rst
  st2common/st2common/router.py
Labels: size/XS

#5730 Add python3.9 to GHA
  .github/workflows/ci.yaml
  .github/workflows/microbenchmarks.yaml
  .github/workflows/orquesta-integration-tests.yaml
  .github/workflows/test.yaml
  CHANGELOG.rst
  lockfiles/st2.lock
  pants.toml
  pylint_plugins/api_models.py
Labels: size/M

#5609 Run st2-self-check in Github Actions
  .github/workflows/ci.yaml
  CHANGELOG.rst
  st2common/bin/st2-self-check
  st2common/bin/st2ctl
Labels: enhancement, size/L

#6045 CI: Update ruby 2.4 -> 2.6 to fix CircleCI Packagecloud deploy step
  .circleci/config.yml
Labels: bug, size/XS, no changelog

#6046 Fix Orquesta Integration Test Codecov Upload
  .github/workflows/orquesta-integration-tests.yaml
  CHANGELOG.rst
  scripts/ci/submit-codecov-coverage.sh
Labels: bug, size/S
