Repository StackStorm/st2, pull requests merged in 2024-05, with the labels that each got.

#6193 Update `oslo.config` to prepare for python 3.10 support.
  .github/workflows/orquesta-integration-tests.yaml
  CHANGELOG.rst
  fixed-requirements.txt
  lockfiles/st2.lock
  requirements-pants.txt
  requirements.txt
  st2actions/requirements.txt
  st2api/requirements.txt
  st2api/tests/unit/test_validation_utils.py
  st2auth/requirements.txt
  st2common/requirements.txt
  st2common/st2common/config.py
  st2reactor/requirements.txt
  st2stream/requirements.txt
  st2tests/st2tests/config.py
  tools/config_gen.py
Labels: external dependency, python3, size/L

#6199 GHA: Refactor repetitive action inputs into in-repo composite actions
  .github/actions/apt-packages/action.yaml
  .github/actions/init-pants/action.yaml
  .github/actions/setup-python/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/lint.yaml
  .github/workflows/microbenchmarks.yaml
  .github/workflows/orquesta-integration-tests.yaml
  .github/workflows/pants.yaml
  .github/workflows/test.yaml
Labels: refactor, size/L, infrastructure: ci/cd, no changelog

#6206 Fix issue with cd'ing in Makefile
  Makefile
Labels: size/XS, infrastructure: ci/cd, maintenance, no changelog
