Repository StackStorm/st2, pull requests merged in 2024-01, with the labels that each got.

#6096 TSC: Promote Mark Mercado (@mamercad) from Contributors to Maintainers
  OWNERS.md
Labels: size/XS, TSC:voting, no changelog

#6091 Add Sravanthi Konduru(sravs-dev) to the Contributors
  OWNERS.md
Labels: size/XS, TSC:voting, no changelog

#6089 Add Scott Swann (jk464) to Contributors
  OWNERS.md
Labels: size/XS, TSC:voting, no changelog

#6088 Add David Culbreth (AndroxxTraxxon) to Contributors
  OWNERS.md
Labels: size/XS, TSC:voting, no changelog

#6087 Promote Carlos (@nzlosh) to Senior Maintainers
  OWNERS.md
Labels: size/XS, TSC:voting, no changelog

#6098 Moving Eugen to Friends
  OWNERS.md
Labels: size/XS, no changelog

#6084 Add Ronnie Hoffmann (@ZoeLeah) to Contributors
  OWNERS.md
Labels: size/XS, TSC:voting, no changelog

#6090 Add Philipp Homberger (@philipphomberger) to Contributors
  OWNERS.md
Labels: size/XS, TSC:voting, no changelog

#6085 Add @enykeev to Contributors
  OWNERS.md
Labels: size/XS, TSC:voting, no changelog

#6086 Add Jeremiah Millay (@floatingstatic) to Contributors
  OWNERS.md
Labels: size/XS, TSC:voting, no changelog

#6118 Bump minimum python version to 3.8 and Upgrade pantsbuild to 2.17
  .github/workflows/ci.yaml
  .github/workflows/lint.yaml
  .github/workflows/microbenchmarks.yaml
  .github/workflows/orquesta-integration-tests.yaml
  .github/workflows/pants.yaml
  .github/workflows/test.yaml
  BUILD
  BUILD.tools
  CHANGELOG.rst
  Makefile
  conf/st2.conf.sample
  contrib/runners/orquesta_runner/tests/unit/test_data_flow.py
  contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
  fixed-requirements.txt
  get-pants.sh
  lockfiles/bandit.lock
  lockfiles/black.lock
  lockfiles/flake8.lock
  lockfiles/pants-plugins.lock
  lockfiles/pylint.lock
  lockfiles/pytest.lock
  lockfiles/setuptools.lock
  lockfiles/st2.lock
  lockfiles/twine.lock
  pants
  pants-plugins/BUILD
  pants-plugins/README.md
  pants-plugins/macros.py
  pants-plugins/pack_metadata/target_types_test.py
  pants-plugins/release/rules.py
  pants-plugins/release/rules_test.py
  pants.toml
  requirements-pants.txt
  requirements.txt
  st2actions/tests/unit/test_actions_registrar.py
  st2api/requirements.txt
  st2api/tests/unit/controllers/v1/test_actions.py
  st2api/tests/unit/controllers/v1/test_packs.py
  st2api/tests/unit/controllers/v1/test_rules.py
  st2auth/st2auth/config.py
  st2client/requirements.txt
  st2common/BUILD
  st2common/requirements.txt
  st2common/st2common/cmd/generate_api_spec.py
  st2common/st2common/util/schema/__init__.py
  st2common/tests/unit/test_configs_registrar.py
  st2common/tests/unit/test_param_utils.py
  st2common/tests/unit/test_service_setup.py
  st2reactor/requirements.txt
  st2stream/requirements.txt
  test-requirements.txt
Labels: external dependency, size/XXL, infrastructure: ci/cd, pantsbuild
