Repository StackStorm/st2, pull requests merged in 2024-09, with the labels that each got.

#6235 Misc CI improvements/fixes
  st2common/st2common/content/bootstrap.py
  st2common/st2common/util/monkey_patch.py
  tools/launchdev.sh
Labels: external dependency, size/S, infrastructure: ci/cd, no changelog

#6140 Add get_result method to st2client
  CHANGELOG.rst
  st2client/st2client/models/core.py
Labels: size/S

#6200 Upgrade pantsbuild from 2.18.3 to 2.20.4 (+regen lockfiles/st2.lock)
  .github/actions/init-pants/action.yaml
  CHANGELOG.rst
  Makefile
  fixed-requirements.txt
  lockfiles/pants-plugins.lock
  lockfiles/st2.lock
  pants.ci.toml
  pants.toml
  requirements.txt
  st2actions/requirements.txt
  st2api/requirements.txt
  st2auth/requirements.txt
  st2client/requirements.txt
  st2common/bin/BUILD
  st2common/requirements.txt
  st2reactor/requirements.txt
  st2stream/requirements.txt
  test-requirements.txt
Labels: tests, external dependency, size/XXL, infrastructure: ci/cd, pantsbuild

#6237 Pants upgrade from 2.20.3 to 2.22.0
  CHANGELOG.rst
  contrib/runners/action_chain_runner/tests/integration/BUILD
  contrib/runners/action_chain_runner/tests/unit/BUILD
  contrib/runners/announcement_runner/tests/integration/BUILD
  contrib/runners/announcement_runner/tests/unit/BUILD
  contrib/runners/http_runner/tests/integration/BUILD
  contrib/runners/http_runner/tests/unit/BUILD
  contrib/runners/inquirer_runner/tests/integration/BUILD
  contrib/runners/inquirer_runner/tests/unit/BUILD
  contrib/runners/local_runner/tests/integration/BUILD
  contrib/runners/local_runner/tests/unit/BUILD
  contrib/runners/noop_runner/tests/integration/BUILD
  contrib/runners/noop_runner/tests/unit/BUILD
  contrib/runners/orquesta_runner/tests/integration/BUILD
  contrib/runners/orquesta_runner/tests/unit/BUILD
  contrib/runners/python_runner/tests/integration/BUILD
  contrib/runners/python_runner/tests/unit/BUILD
  contrib/runners/remote_runner/tests/integration/BUILD
  contrib/runners/remote_runner/tests/unit/BUILD
  contrib/runners/winrm_runner/tests/integration/BUILD
  contrib/runners/winrm_runner/tests/unit/BUILD
  lockfiles/pants-plugins.lock
  pants.toml
  scripts/github/install-apt-packages-use-cache.sh
  st2actions/tests/integration/BUILD
  st2actions/tests/unit/BUILD
  st2api/tests/integration/BUILD
  st2api/tests/unit/BUILD
  st2auth/tests/integration/BUILD
  st2auth/tests/unit/BUILD
  st2client/tests/integration/BUILD
  st2client/tests/unit/BUILD
  st2common/benchmarks/BUILD
  st2common/tests/integration/BUILD
  st2common/tests/unit/BUILD
  st2reactor/tests/integration/BUILD
  st2reactor/tests/unit/BUILD
  st2stream/tests/integration/BUILD
  st2stream/tests/unit/BUILD
  st2tests/integration/BUILD
  st2tests/tests/unit/BUILD
Labels: size/L, infrastructure: ci/cd, pantsbuild

#6239 test changes from #6236
  .gitignore
  contrib/runners/python_runner/tests/integration/test_python_action_process_wrapper.py
  st2api/tests/unit/controllers/v1/test_service_registry.py
  st2client/tests/unit/test_commands.py
  st2client/tests/unit/test_inquiry.py
  st2common/st2common/services/coordination.py
  st2common/st2common/transport/publishers.py
  st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume_with_error.yaml
Labels: tests, python3, size/M, no changelog

#6229 Pants upgrade from 2.22.0 to 2.23.0a0
  .gitattributes
  CHANGELOG.rst
  contrib/chatops/tests/BUILD
  contrib/core/tests/BUILD
  contrib/examples/tests/BUILD
  contrib/linux/tests/BUILD
  contrib/packs/tests/BUILD
  lockfiles/pants-plugins.lock
  pants.toml
  st2common/tests/unit/test_dist_utils.py
Labels: size/L, infrastructure: ci/cd, pantsbuild

#6240 Pants: Use python imports to identify fixtures
  CHANGELOG.rst
  contrib/runners/python_runner/tests/unit/test_pythonrunner.py
  st2api/tests/unit/controllers/v1/test_packs.py
  st2api/tests/unit/controllers/v1/test_packs_views.py
  st2api/tests/unit/controllers/v1/test_sensortypes.py
  st2common/st2common/content/loader.py
  st2common/tests/resources/BUILD
  st2common/tests/resources/fixture.py
  st2common/tests/resources/loadableplugin/BUILD
  st2common/tests/resources/loadableplugin/fixture.py
  st2common/tests/resources/packs/BUILD
  st2common/tests/resources/packs/fixture.py
  st2common/tests/resources/packs2/BUILD
  st2common/tests/resources/packs2/fixture.py
  st2common/tests/resources/packs3/BUILD
  st2common/tests/resources/packs3/fixture.py
  st2common/tests/resources/packs3/overrides/_global.yaml
  st2common/tests/resources/packs3/overrides/overpack1.yaml
  st2common/tests/resources/packs3/overrides/overpack2.yaml
  st2common/tests/resources/packs3/overrides/overpack3.yaml
  st2common/tests/resources/packs3/overrides/overpack4.yaml
  st2common/tests/unit/test_content_loader.py
  st2common/tests/unit/test_logger.py
  st2common/tests/unit/test_plugin_loader.py
  st2reactor/tests/resources/BUILD
  st2reactor/tests/resources/fixture.py
  st2reactor/tests/unit/test_sensor_wrapper.py
Labels: tests, size/L, infrastructure: ci/cd, pantsbuild

#6242 Add `ST2TESTS_SYSTEM_USER` env var to set `system_user.user` in tests
  .github/workflows/test.yaml
  CHANGELOG.rst
  contrib/runners/orquesta_runner/tests/unit/test_basic.py
  contrib/runners/orquesta_runner/tests/unit/test_context.py
  contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
  pants.toml
  st2actions/tests/unit/test_runner_container.py
  st2api/tests/unit/controllers/v1/test_alias_execution.py
  st2api/tests/unit/controllers/v1/test_auth.py
  st2api/tests/unit/controllers/v1/test_executions.py
  st2tests/st2tests/config.py
Labels: tests, size/M

#6241 Clean up import side effects in tests
  CHANGELOG.rst
  st2actions/tests/unit/policies/test_base.py
  st2actions/tests/unit/policies/test_concurrency.py
  st2actions/tests/unit/policies/test_concurrency_by_attr.py
  st2actions/tests/unit/test_action_runner_worker.py
  st2actions/tests/unit/test_execution_cancellation.py
  st2actions/tests/unit/test_executions.py
  st2actions/tests/unit/test_notifier.py
  st2actions/tests/unit/test_output_schema.py
  st2actions/tests/unit/test_parallel_ssh.py
  st2actions/tests/unit/test_paramiko_remote_script_runner.py
  st2actions/tests/unit/test_paramiko_ssh.py
  st2actions/tests/unit/test_paramiko_ssh_runner.py
  st2actions/tests/unit/test_queue_consumers.py
  st2actions/tests/unit/test_remote_runners.py
  st2actions/tests/unit/test_runner_container.py
  st2actions/tests/unit/test_scheduler.py
  st2actions/tests/unit/test_scheduler_entrypoint.py
  st2actions/tests/unit/test_scheduler_retry.py
  st2actions/tests/unit/test_worker.py
  st2actions/tests/unit/test_workflow_engine.py
  st2common/tests/unit/services/test_policy.py
  st2common/tests/unit/services/test_workflow.py
  st2common/tests/unit/services/test_workflow_cancellation.py
  st2common/tests/unit/services/test_workflow_identify_orphans.py
  st2common/tests/unit/services/test_workflow_rerun.py
  st2common/tests/unit/services/test_workflow_service_retries.py
  st2common/tests/unit/test_action_alias_utils.py
  st2common/tests/unit/test_executions_util.py
  st2common/tests/unit/test_jinja_render_data_filters.py
  st2common/tests/unit/test_jsonify.py
  st2common/tests/unit/test_logging_middleware.py
  st2common/tests/unit/test_operators.py
  st2common/tests/unit/test_purge_rule_enforcement.py
  st2common/tests/unit/test_purge_task_executions.py
  st2common/tests/unit/test_purge_token.py
  st2common/tests/unit/test_purge_trace.py
  st2common/tests/unit/test_purge_worklows.py
  st2common/tests/unit/test_runners_utils.py
  st2common/tests/unit/test_util_payload.py
  st2reactor/tests/unit/test_garbage_collector.py
  st2reactor/tests/unit/test_process_container.py
Labels: tests, size/L, infrastructure: ci/cd, pantsbuild

#6245 Make unit tests use redis
  .github/workflows/ci.yaml
  CHANGELOG.rst
  Makefile
  st2actions/tests/unit/test_policies.py
  st2actions/tests/unit/test_worker.py
  st2actions/tests/unit/test_workflow_engine.py
  st2common/tests/unit/services/test_workflow_service_retries.py
  st2common/tests/unit/test_service_setup.py
  st2tests/st2tests/config.py
Labels: tests, service: workflow engine, size/L, infrastructure: ci/cd

#6244 pants: Add `system_user` detection to `pants-plugins/uses_services` (+ `mongo` detection improvements)
  CHANGELOG.rst
  contrib/runners/orquesta_runner/tests/unit/BUILD
  pants-plugins/uses_services/BUILD
  pants-plugins/uses_services/mongo_rules.py
  pants-plugins/uses_services/register.py
  pants-plugins/uses_services/scripts/has_system_user.py
  pants-plugins/uses_services/scripts/is_mongo_running.py
  pants-plugins/uses_services/system_user_rules.py
  pants-plugins/uses_services/system_user_rules_test.py
  pants-plugins/uses_services/target_types.py
  st2actions/tests/unit/BUILD
  st2api/tests/unit/controllers/v1/BUILD
  st2common/tests/unit/BUILD
Labels: size/L, infrastructure: ci/cd, pantsbuild

#6250 Rename `[database].ssl*` options to `[database].tls*` to support pymongo 4
  CHANGELOG.rst
  conf/st2.conf.sample
  contrib/packs/actions/pack_mgmt/unload.py
  pants-plugins/sample_conf/rules.py
  st2common/st2common/config.py
  st2common/st2common/database_setup.py
  st2common/st2common/models/db/__init__.py
  st2common/st2common/persistence/cleanup.py
  st2common/st2common/persistence/db_init.py
  st2common/tests/unit/test_db.py
  st2reactor/st2reactor/container/sensor_wrapper.py
  tools/config_gen.py
Labels: enhancement, breaking change, external dependency, mongodb, size/XL, migrations

#6252 Deps: Update mongoengine to 0.29.1 and pymongo 4.6.3
  CHANGELOG.rst
  Makefile
  fixed-requirements.txt
  lockfiles/st2.lock
  pants-plugins/uses_services/scripts/is_mongo_running.py
  requirements-pants.txt
  requirements.txt
  st2actions/requirements.txt
  st2api/requirements.txt
  st2auth/requirements.txt
  st2client/requirements.txt
  st2common/bin/migrations/v3.8/st2-drop-st2exporter-marker-collections
  st2common/requirements.txt
  st2common/st2common/models/db/__init__.py
  st2common/st2common/models/db/stormbase.py
  st2common/tests/unit/base.py
  st2common/tests/unit/test_db.py
  st2reactor/requirements.txt
  st2stream/requirements.txt
Labels: enhancement, external dependency, database, mongodb, size/XL

#6251 Pantsbuild: Add BUILD dependencies for logging.conf
  BUILD
  CHANGELOG.rst
  pants-plugins/macros.py
  st2actions/conf/BUILD
  st2api/conf/BUILD
  st2auth/conf/BUILD
  st2reactor/conf/BUILD
  st2stream/conf/BUILD
  st2tests/conf/BUILD
  st2tests/st2tests/fixtures/conf/BUILD
Labels: size/M, infrastructure: ci/cd, pantsbuild

#6246 Update from Mongo 4.4 to Mongo 7 in CI
  .github/workflows/ci.yaml
  .github/workflows/microbenchmarks.yaml
  .github/workflows/orquesta-integration-tests.yaml
  .github/workflows/test.yaml
  CHANGELOG.rst
  Makefile
Labels: tests, mongodb, size/M, infrastructure: ci/cd

#6253 Pants: Minor test refactor to support running under pants+pytest
  CHANGELOG.rst
  contrib/core/BUILD
  contrib/core/actions/send_mail/BUILD
  st2common/tests/unit/services/test_packs.py
  st2common/tests/unit/test_db.py
  st2common/tests/unit/test_util_file_system.py
  st2tests/st2tests/policies/meta/BUILD
Labels: tests, size/M, infrastructure: ci/cd, pantsbuild

#6254 Pants: Add more dependency-related BUILD metadata
  BUILD
  CHANGELOG.rst
  contrib/chatops/actions/BUILD
  contrib/chatops/actions/templates/BUILD
  contrib/chatops/tests/BUILD
  contrib/core/tests/BUILD
  contrib/packs/tests/BUILD
  contrib/runners/action_chain_runner/tests/BUILD
  contrib/runners/action_chain_runner/tests/unit/BUILD
  contrib/runners/announcement_runner/tests/BUILD
  contrib/runners/http_runner/tests/BUILD
  contrib/runners/inquirer_runner/tests/BUILD
  contrib/runners/local_runner/tests/BUILD
  contrib/runners/noop_runner/tests/BUILD
  contrib/runners/orquesta_runner/tests/BUILD
  contrib/runners/orquesta_runner/tests/unit/BUILD
  contrib/runners/python_runner/tests/BUILD
  contrib/runners/python_runner/tests/integration/BUILD
  contrib/runners/python_runner/tests/unit/BUILD
  contrib/runners/remote_runner/tests/BUILD
  contrib/runners/winrm_runner/tests/BUILD
  st2actions/tests/unit/BUILD
  st2actions/tests/unit/policies/BUILD
  st2api/tests/unit/BUILD
  st2api/tests/unit/controllers/BUILD
  st2api/tests/unit/controllers/v1/BUILD
  st2auth/tests/unit/BUILD
  st2auth/tests/unit/controllers/v1/BUILD
  st2common/tests/fixtures/local_runner/BUILD
  st2common/tests/unit/BUILD
  st2common/tests/unit/services/BUILD
  st2reactor/tests/unit/BUILD
  st2stream/tests/unit/controllers/v1/BUILD
  st2tests/st2tests/fixtures/generic/BUILD
Labels: enhancement, size/L, infrastructure: ci/cd, pantsbuild
