Repository StackStorm/st2, pull requests merged in 2024-04, with the labels that each got.

#6164 update pants st2.lock file
  lockfiles/st2.lock
Labels: size/L

#6120 Upgrade Pantsbuild to 2.18
  CHANGELOG.rst
  lint-configs/regex-lint.yaml
  lockfiles/bandit.lock
  lockfiles/black.lock
  lockfiles/flake8.lock
  lockfiles/pants-plugins.lock
  lockfiles/pylint.lock
  lockfiles/pytest.lock
  lockfiles/st2.lock
  lockfiles/twine.lock
  pants-plugins/README.md
  pants.toml
Labels: size/XXL, pantsbuild

#6181 Pants requirements
  CHANGELOG.rst
  Makefile
  contrib/runners/winrm_runner/requirements.txt
  fixed-requirements.txt
  lockfiles/st2-constraints.txt
  lockfiles/st2.lock
  requirements-pants.txt
  requirements.txt
  st2actions/requirements.txt
  st2api/requirements.txt
  st2auth/requirements.txt
  st2client/requirements.txt
  st2common/bin/st2-run-pack-tests
  st2common/requirements.txt
  st2reactor/requirements.txt
  st2stream/requirements.txt
  st2tests/requirements.txt
  st2tests/st2tests/fixtures/packs/test_library_dependencies/requirements.txt
  test-requirements.txt
Labels: external dependency, size/XL, pantsbuild

#6185 Improve testing logic in Makefile
  Makefile
Labels: tests, size/M, infrastructure: ci/cd, maintenance, no changelog

#6080 Drop Python 3.6 testing for ST2 3.9.0
  .circleci/config.yml
  CHANGELOG.rst
Labels: size/XS

#6184 st2test Popen.pid bugfix
  CHANGELOG.rst
  st2tests/st2tests/base.py
Labels: tests, size/XS, bug fix

#6183 Add support for loading `.pth` files in st2 venv
  .github/workflows/ci.yaml
  CHANGELOG.rst
  st2common/bin/st2-run-pack-tests
  st2common/st2common/util/sandboxing.py
  st2common/st2common/util/virtualenvs.py
  st2common/tests/unit/test_util_sandboxing.py
  st2reactor/tests/integration/test_sensor_container.py
Labels: feature, python3, size/L, packs, pantsbuild

#6186 Refactor tools/launchdev.sh to use tmux
  .github/workflows/ci.yaml
  CHANGELOG.rst
  dev_docs/Troubleshooting_Guide.rst
  scripts/github/prepare-integration.sh
  tools/launchdev.sh
  tools/screen-configs/st2actionrunner.conf
  tools/screen-configs/st2api.conf
  tools/screen-configs/st2auth.conf
  tools/screen-configs/st2garbagecollector.conf
  tools/screen-configs/st2notifier.conf
  tools/screen-configs/st2rulesengine.conf
  tools/screen-configs/st2scheduler.conf
  tools/screen-configs/st2sensorcontainer.conf
  tools/screen-configs/st2stream.conf
  tools/screen-configs/st2timersengine.conf
  tools/screen-configs/st2workflowengine.conf
Labels: refactor, tests, size/L, infrastructure: ci/cd

#6191 Update pylint to 3.1.0
  contrib/examples/actions/ubuntu_pkg_info/ubuntu_pkg_info.py
  contrib/packs/actions/pack_mgmt/get_pack_dependencies.py
  lint-configs/python/.pylintrc
  lockfiles/pylint.lock
  pylint_plugins/BUILD
  pylint_plugins/api_models.py
  pylint_plugins/api_models_test.py
  pylint_plugins/db_models.py
  pyproject.toml
  st2actions/st2actions/container/base.py
  st2common/bin/migrations/v3.5/st2-migrate-db-dict-field-values
  st2common/st2common/services/action.py
  test-requirements.txt
Labels: external dependency, size/L, infrastructure: ci/cd, maintenance, no changelog

#6188 Fix misc DeprecationWarnings
  CHANGELOG.rst
  st2actions/st2actions/policies/concurrency_by_attr.py
  st2actions/st2actions/scheduler/handler.py
  st2api/st2api/controllers/v1/triggers.py
  st2client/st2client/base.py
  st2client/st2client/config_parser.py
  st2client/st2client/formatters/execution.py
  st2client/st2client/shell.py
  st2client/tests/unit/test_config_parser.py
  st2client/tests/unit/test_shell.py
  st2common/st2common/constants/meta.py
  st2common/st2common/expressions/functions/version.py
  st2common/st2common/logging/misc.py
  st2common/st2common/persistence/db_init.py
  st2common/st2common/services/coordination.py
  st2common/st2common/services/trigger_dispatcher.py
  st2common/st2common/util/api.py
  st2common/st2common/util/loader.py
  st2common/st2common/util/versioning.py
  st2reactor/st2reactor/container/sensor_wrapper.py
  st2tests/st2tests/fixtures/packs/dummy_pack_23/actions/workflows/__init__.py
Labels: enhancement, size/L, maintenance

#6189 Update st2client deps: editor and prompt-toolkit
  CHANGELOG.rst
  fixed-requirements.txt
  lockfiles/st2.lock
  requirements-pants.txt
  requirements.txt
  st2client/in-requirements.txt
  st2client/requirements.txt
  st2client/st2client/commands/pack.py
  st2client/st2client/utils/interactive.py
  st2common/requirements.txt
  test-requirements.txt
Labels: enhancement, external dependency, size/L
